// -----------------------------------------------------------------
// This file is automatically generated by "kdu_text_extractor"
// Do not edit the file directly.  You may, however, use this file
// as a template for alternate versions in which the text strings
// are translated into different languages.
// -----------------------------------------------------------------
#include <kdu_messaging.h>

struct kdl_message_info{
  const char *context;
  kdu_uint32 id;
  const char *lead_in;
  const char *text;
};

static bool
  kdl_register_text(kdl_message_info *info, int num_records)
{
  for (; num_records > 0; num_records--, info++)
    kdu_customize_text(info->context,info->id,
                       info->lead_in,info->text);
  return true;
}

static kdl_message_info data[75] = {
  {
    "E(kdu_client.cpp)", 1,
    "Error in Kakadu Client:\n",
    "Unable to resolve host address\0"
  },
  {
    "E(kdu_client.cpp)", 2,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 3,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 4,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 5,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 6,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 7,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 8,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 9,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 10,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL.  At least one descriptor must appear in the body of the request field.  Query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 11,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL.  Problem encountered at:\n\n\t\0"
    "\n\nComplete query string is:\n\n\t\0"
  },
  {
    "E(kdu_client.cpp)", 12,
    "Error in Kakadu Client:\n",
    "Unable to complete primary request channel connection.\0"
  },
  {
    "E(kdu_client.cpp)", 13,
    "Error in Kakadu Client:\n",
    "Unable to connect auxiliary TCP channel to server.\0"
  },
  {
    "E(kdu_client.cpp)", 14,
    "Error in Kakadu Client:\n",
    "Server reply to client window request does not appear to contain an HTTP version number as the first token.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 15,
    "Error in Kakadu Client:\n",
    "Server reply to client window request does not appear to contain a status code as the second token.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 16,
    "Error in Kakadu Client:\n",
    "Server could not process client window request.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 18,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Expected a strictly positive byte limit parameter.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 19,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Expected positive horizontal and vertical dimensions, separated only by a comma.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 20,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Expected non-negative horizontal and vertical offsets from the upper left hand corner of the requested image resolution.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 21,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Expected non-negative horizontal and vertical dimensions for the region of interest within the requested image resolution.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 22,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 23,
    "Error in Kakadu Client:\n",
    "Illegal translation identifier in\0"
    "header in server's reply to window request.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 24,
    "Error in Kakadu Client:\n",
    "Illegal translation identifier in\0"
    "header in server's reply to window request.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 25,
    "Error in Kakadu Client:\n",
    "Illegal value or range in\0"
    "header in server's reply to window request.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 26,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 27,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Expected non-negative maximum number of quality layers.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 28,
    "Error in Kakadu Client:\n",
    "Incorrectly formatted\0"
    "header in server's reply to window request.  Error encountered at:\n\n\t\n\nComplete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 29,
    "Error in Kakadu Client:\n",
    "Server appears to have issued a new unique target identifier, while we were in the middle of browsing the image.  Most likely, the image has been modified on the server and you should re-open it.\0"
  },
  {
    "E(kdu_client.cpp)", 30,
    "Error in Kakadu Client:\n",
    "Server has responded with a successful status code, but has not included a\0"
    "response header, even though we requested the target-id with a\0"
    "request field.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 31,
    "Error in Kakadu Client:\n",
    "Server appears to have issued a new channel ID where none was requested!!\0"
  },
  {
    "E(kdu_client.cpp)", 34,
    "Error in Kakadu Client:\n",
    "HTTP response body terminated before sufficient compressed data was received to correctly parse all server messages!\0"
  },
  {
    "E(kdu_client.cpp)", 35,
    "Error in Kakadu Client:\n",
    "Unrecognized channel transport type\0"
  },
  {
    "E(kdu_client.cpp)", 36,
    "Error in Kakadu Client:\n",
    "Server response has an unacceptable content type.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 37,
    "Error in Kakadu Client:\n",
    "Malformed \"Content-length\" header in HTTP response message.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 38,
    "Error in Kakadu Client:\n",
    "Expected non-negative hex-encoded chunk length on line:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 39,
    "Error in Kakadu Client:\n",
    "Illegal chunk length found in server return data sent on the auxiliary TCP channel.  Chunk lengths must include the length of the 8-byte chunk preamble, which contains the chunk length value itself.  This means that the length may not be less than 8.  Got a value of \0"
  },
  {
    "E(kdu_client.cpp)", 41,
    "Error in Kakadu Client:\n",
    "Illegal message header encountered in response message sent by server.\0"
  },
  {
    "E(kdu_client.cpp)", 42,
    "Error in Kakadu Client:\n",
    "Received a JPIP stream message containing an illegal header or one which contains a ridiculously large parameter.\0"
  },
  {
    "E(kdu_client.cpp)", 34015489,
    "Error in Kakadu Client:\n",
    "Malformed \0"
    "field in query component of requested URL; query string is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 34082817,
    "Error in Kakadu Client:\n",
    "Illegal data chunk received from server over auxiliary UDP channel.  UDP data chunks must contain a whole number of JPIP messages, all of which must belong to a single request.\0"
  },
  {
    "E(kdu_client.cpp)", 34082818,
    "Error in Kakadu Client:\n",
    "Server has created a JPIP channel which uses an unreliable transport, yet the client request for a new channel did not include any unreliable transports.  This situation is both illegal on the part of the server and dangerous for the client, because clients need to take special steps when issuing requests on unreliable channels to prevent inconsistency with requests on other JPIP channels.  We were unable to anticipated the possibility of an unreliable transport, since we did not request one.\0"
  },
  {
    "E(kdu_client.cpp)", 67637249,
    "Error in Kakadu Client:\n",
    "Unable to connect auxiliary UDP channel to server.\0"
  },
  {
    "E(kdu_client.cpp)", 100862209,
    "Error in Kakadu Client:\n",
    "You must supply a non-empty resource string or a compatible URL in the call to `kdu_client::connect'.\0"
  },
  {
    "E(kdu_client.cpp)", 100862210,
    "Error in Kakadu Client:\n",
    "Illegal port number found in server/proxy address suffix\0"
    "in call to `kdu_client::connect' (or possibly in a JPIP-cnew response header).\0"
  },
  {
    "E(kdu_client.cpp)", 302188801,
    "Error in Kakadu Client:\n",
    "Cannot understand \"Transfer-encoding\" header in HTTP response message.  Expect chunked transfer encoding, or a \"Content-length\" header.  Complete server response is:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 318966017,
    "Error in Kakadu Client:\n",
    "Server has failed to include a non-empty new channel-id in the set of channel parameters returned via the\0"
    "header in its HTTP reply paragraph.  Complete server reply paragraph was:\n\n\0"
  },
  {
    "E(kdu_client.cpp)", 318966018,
    "Error in Kakadu Client:\n",
    "Attempting to make an internal copy of a string (probably a network supplied name) which is ridiculously long (more than 65K characters).  The copy is being aborted to avoid potential exploitation by malicious network agents.\0"
  },
  {
    "E(kdu_client.cpp)", 318966019,
    "Error in Kakadu Client:\n",
    "Attempting to make a temporary copy of a string (probably a network supplied name) which is ridiculously long (more than 65K characters).  The copy is being aborted to avoid potential exploitation by malicious network agents.\0"
  },
  {
    "E(kdu_client.cpp)", 318966020,
    "Error in Kakadu Client:\n",
    "Attempting to make a temporary buffer to store data (probably based on network-supplied parameters) which is ridiculously long (more than 65K characters).  The allocation is being aborted to avoid potential exploitation by malicious network agents.\0"
  },
  {
    "E(kdu_client.cpp)", 335743233,
    "Error in Kakadu Client:\n",
    "Server's response data seems to be getting ahead of receiver's requests!!!  All outstanding response data for issued requests on an HTTP-TCP/UDP JPIP channel have been received over the auxiliary channel, yet there is still more data available!\0"
  },
  {
    "E(kdu_client.cpp)", 419629313,
    "Error in Kakadu Client:\n",
    "Primary channel connection attempt timed out!\0"
  },
  {
    "E(kdu_client.cpp)", 419629314,
    "Error in Kakadu Client:\n",
    "Auxiliary return channel connection attempt timed out!\0"
  },
  {
    "E(kdu_client.cpp)", 537331969,
    "Error in Kakadu Client:\n",
    "Server response contains an HTTP body with a non-terminal EOR message!  EOR messages may appear only at the end of a response to any given request.\0"
  },
  {
    "E(kdu_client.cpp)", 604178689,
    "Error in Kakadu Client:\n",
    "Primary channel connection failed!\0"
  },
  {
    "E(kdu_client.cpp)", 604178690,
    "Error in Kakadu Client:\n",
    "Auxiliary return channel connection attempt failed!\0"
  },
  {
    "E(kdu_client.cpp)", 621088769,
    "Error in Kakadu Client:\n",
    "Illegal server/proxy address -- bracketed portion of address\0"
    "suggests an IP literal, which should be followed immediately by any \":<port>\" suffix, in call to `kdu_client::connect' (or possibly in a JPIP-cnew response header).\0"
  },
  {
    "E(kdu_client.cpp)", 688328705,
    "Error in Kakadu Client:\n",
    "Illegal datagram length found in server return data sent on the auxiliary UDP channel.  Datagrams must include the 8-byte chunk preamble, so they cannot be smaller than 8 bytes in length.  Got a datagram with length \0"
  },
  {
    "E(kdu_clientx.cpp)", 0,
    "Error in Kakadu Client:\n",
    "Malformed codestream registration box encountered in JPX compositing layer header box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 1,
    "Error in Kakadu Client:\n",
    "Malformed codestream registration box encountered in JPX compositing layer header box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 3,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "E(kdu_clientx.cpp)", 4,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "E(kdu_clientx.cpp)", 5,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "E(kdu_clientx.cpp)", 6,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "E(kdu_clientx.cpp)", 352391937,
    "Error in Kakadu Client:\n",
    "Invalid Compositing Layer Header box found within a Compositing Layer Extensions box.  Since no Codestream Registration box is supplied, the compositing layer must use a codestream with the same absolute index; however, the associated codestream is neither a top-level codestream, nor one of the codestreams defined within the Compositing Layer Extensions box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 352391938,
    "Error in Kakadu Client:\n",
    "Top-level Codestream Header boxes must all precede any Compositing Layer Extensions boxes in a JPX file.\0"
  },
  {
    "E(kdu_clientx.cpp)", 352391939,
    "Error in Kakadu Client:\n",
    "Top-level Compositing Layer boxes must all precede any Compositing Layer Extensions boxes in a JPX file.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169153,
    "Error in Kakadu Client:\n",
    "Compositing Layer Extensions box must be preceded by a Composition box, at least one Codestream Header box and at least one Compositing Layer Header box at the top level of the file.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169156,
    "Error in Kakadu Client:\n",
    "Error in Compositing Layer Extensions box: first sub-box must be a Compositing Layer Extensions Info box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169157,
    "Error in Kakadu Client:\n",
    "Error in Compositing Layer Extensions Info box: box appears to be prematurely truncated.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169158,
    "Error in Kakadu Client:\n",
    "Too many Codestream Header sub-boxes found within Compositing Layer Extensions box, compared with value supplied by the Info sub-box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169159,
    "Error in Kakadu Client:\n",
    "Too many Compositing Layer Header sub-boxes found within Compositing Layer Extensions box, compared with value supplied by the Info sub-box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 369169160,
    "Error in Kakadu Client:\n",
    "Too few Compositing Layer Header or Codestream Header sub-boxes found within Compositing Layer Extensions box, compared with value supplied by the Info sub-box.\0"
  },
  {
    "E(kdu_clientx.cpp)", 688132609,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "E(kdu_clientx.cpp)", 688132610,
    "Error in Kakadu Client:\n",
    "Malformed Instruction Set box found in JPX data source.\0"
  },
  {
    "W(kdu_client.cpp)", 33818881,
    "Warning in Kakadu Client:\n",
    "Server has assigned the same JPIP Channel ID to a new channel (via a\0"
    "response header) as that used for a previously assigned JPIP channel.  This is probably illegal, unless the server has only just closed the old channel, in which case it is just very bad practice.\0"
  }
};

static bool dummy_val = kdl_register_text(data,75);

#ifndef KDU_EXCLUDE_DEVELOPER_TEXT

static kdl_message_info dev_data[2] = {
  {
    "E(kdu_client.cpp)", 0,
    "Error in Kakadu Client:\n",
    "You may not install a new client context translator, over the top of an existing one, while the `kdu_client' object is active (from `connect' to `close').\0"
  },
  {
    "E(kdu_client.cpp)", 43,
    "Error in Kakadu Client:\n",
    "You must supply a server name or a compatible URL in the call to `kdu_client::connect'.\0"
  }
};

static bool dev_dummy_val = kdl_register_text(dev_data,2);

#endif // !KDU_EXCLUDE_DEVELOPER_TEXT
