// -----------------------------------------------------------------
// This file is automatically generated by "kdu_text_extractor"
// Do not edit the file directly.  You may, however, use this file
// as a template for alternate versions in which the text strings
// are translated into different languages.
// -----------------------------------------------------------------
#include <kdu_messaging.h>

struct kdl_message_info{
  const char *context;
  kdu_uint32 id;
  const char *lead_in;
  const char *text;
};

static bool
  kdl_register_text(kdl_message_info *info, int num_records)
{
  for (; num_records > 0; num_records--, info++)
    kdu_customize_text(info->context,info->id,
                       info->lead_in,info->text);
  return true;
}

static kdl_message_info data[16] = {
  {
    "E(jpb.cpp)", 4,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize `jpb_target' with parameters that require more than 100 distinct FF values to be used when generating timecodes.  Legal timecodes are a required feature of any elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 8,
    "Error in Kakadu File Format Support:\n",
    "Codestreams embedded within an elementary broadcast stream must have a BROADCAST or DIGITAL CINEMA profile.\0"
  },
  {
    "E(jpb.cpp)", 9,
    "Error in Kakadu File Format Support:\n",
    "Profile of codestream being embedded in an elementary broadcast stream is not compatible with the maximum bit-rate declared in the stream's `BRAT' box.  Suspect you are encoding to a bit-rate higher than that supported by the profile.  The maximum bit-rate for the codestream's profile is \0"
  },
  {
    "E(jpb.cpp)", 10,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write a codestream that exceeds the maximum allowable size for any field/frame for the open elementary broadcast stream.  Perhaps you have included informational marker segments (for random access) in the codestream but have failed to allow for their size in the specified rate limit supplied to `kdu_codestream::flush'.  Rate limitations are applied to all codestream content and all non-optional headers, but PLT marker segments are not automatically accounted for ahead of time, partly because some codestream generation orders may not allow precise determination of the size of these headers.\0"
  },
  {
    "E(jpb.cpp)", 11,
    "Error in Kakadu File Format Support:\n",
    "Elemetary broadcast stream super-box contains multiple `FRAT' (frame-rate) sub-boxes.\0"
  },
  {
    "E(jpb.cpp)", 12,
    "Error in Kakadu File Format Support:\n",
    "Invalid `FRAT' (frame-rate) sub-box encountered while parsing elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 13,
    "Error in Kakadu File Format Support:\n",
    "Elemetary broadcast stream super-box contains multiple `BRAT' (max bit-rate) sub-boxes.\0"
  },
  {
    "E(jpb.cpp)", 14,
    "Error in Kakadu File Format Support:\n",
    "Invalid `BRAT' (max bit-rate) sub-box encountered while parsing elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 15,
    "Error in Kakadu File Format Support:\n",
    "Elemetary broadcast stream super-box contains multiple `FIEL' (field coding) sub-boxes.\0"
  },
  {
    "E(jpb.cpp)", 16,
    "Error in Kakadu File Format Support:\n",
    "Invalid `BRAT' (max bit-rate) sub-box encountered while parsing elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 17,
    "Error in Kakadu File Format Support:\n",
    "Elemetary broadcast stream super-box contains multiple `TCOD' (timecode) sub-boxes.\0"
  },
  {
    "E(jpb.cpp)", 18,
    "Error in Kakadu File Format Support:\n",
    "Invalid `TCOD' (timecode) sub-box encountered while parsing elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 19,
    "Error in Kakadu File Format Support:\n",
    "Elemetary broadcast stream super-box contains multiple `BCOL' (broadcast colour) sub-boxes.\0"
  },
  {
    "E(jpb.cpp)", 20,
    "Error in Kakadu File Format Support:\n",
    "Invalid `BCOL' (broadcast colour) sub-box encountered while parsing elementary broadcast stream.\0"
  },
  {
    "E(jpb.cpp)", 21,
    "Error in Kakadu File Format Support:\n",
    "Encountered invalid `ELSM' (elementary broadcast stream) super-box in source file; one or more required sub-boxes are missing.\0"
  },
  {
    "E(jpb.cpp)", 23,
    "Error in Kakadu File Format Support:\n",
    "Source file does not appear to contain an elementary broadcast stream.  First box was not an `ELSM' super-box.\0"
  }
};

static bool dummy_val = kdl_register_text(data,16);

#ifndef KDU_EXCLUDE_DEVELOPER_TEXT

static kdl_message_info dev_data[10] = {
  {
    "E(jpb.cpp)", 1,
    "Error in Kakadu File Format Support:\n",
    "`jpb_target::open' requires strictly positive values for the `timescale', `frame_duration' and `max_bitrate' arguments.\0"
  },
  {
    "E(jpb.cpp)", 3,
    "Error in Kakadu File Format Support:\n",
    "Unrecognized frame colour space passed to `jpb_target'.  Valid colour space identifiers for elementary broadcast streams must be 1-byte integers in the range 0 to 5.\0"
  },
  {
    "E(jpb.cpp)", 5,
    "Error in Kakadu File Format Support:\n",
    "Illegal initial timecode passed to `jpb_target'.  Each byte of a valid timecode must hold 2 decimal digits in BCD format, with the fields satisfying HH<24, MM<60 and SS<60 and FF < ceil(frame-rate).\0"
  },
  {
    "E(jpb.cpp)", 6,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `jpb_target:open_image' without first closing an existing open image.\0"
  },
  {
    "E(jpb.cpp)", 7,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `jpb_target::close_image' without first writing some content to an open image.\0"
  },
  {
    "E(jpb.cpp)", 22,
    "Error in Kakadu File Format Support:\n",
    "Unable to seek to previously parsed frame within elementary broadcast stream.  Most likely cause is a lack of support for seeking within the file source.\0"
  },
  {
    "E(jpb.cpp)", 24,
    "Error in Kakadu File Format Support:\n",
    "The `jpb_source::seek_to_frame' function may not be called until any image opened with `open_image' has been closed.\0"
  },
  {
    "E(jpb.cpp)", 25,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `jpb_source::open_image' without first closing a previously opened image.\0"
  },
  {
    "E(jpb.cpp)", 67441153,
    "Error in Kakadu File Format Support:\n",
    "Illegal timecode passed to `jpb_target::set_timecode'.  Each byte of a valid timecode must hold 2 decimal digits in BCD format, with the fields satisfying HH<24, MM<60, SS<60 and FF < ceil(frame-rate).\0"
  },
  {
    "W(jpb.cpp)", 30,
    "Warning in Kakadu File Format Support:\n",
    "Application-supplied timecode required adjustment to conform to the drop-frame timecode generation rules set up by `jpb_target::open'.  To avoid this, specify the `JPB_TIMEFLAG_NDF' flag to disable the drop-frame timecode generation algorithm.\0"
  }
};

static bool dev_dummy_val = kdl_register_text(dev_data,10);

#endif // !KDU_EXCLUDE_DEVELOPER_TEXT
