// -----------------------------------------------------------------
// This file is automatically generated by "kdu_text_extractor"
// Do not edit the file directly.  You may, however, use this file
// as a template for alternate versions in which the text strings
// are translated into different languages.
// -----------------------------------------------------------------
#include <kdu_messaging.h>

struct kdl_message_info{
  const char *context;
  kdu_uint32 id;
  const char *lead_in;
  const char *text;
};

static bool
  kdl_register_text(kdl_message_info *info, int num_records)
{
  for (; num_records > 0; num_records--, info++)
    kdu_customize_text(info->context,info->id,
                       info->lead_in,info->text);
  return true;
}

static kdl_message_info data[103] = {
  {
    "E(jpx.cpp)", 0,
    "Error in Kakadu File Format Support:\n",
    "Error encountered reading fragment list (flst) box.  Unable to read the initial fragment count.\0"
  },
  {
    "E(jpx.cpp)", 1,
    "Error in Kakadu File Format Support:\n",
    "Error encountered reading fragment list (flst) box.  Contents of box terminated prematurely.\0"
  },
  {
    "E(jpx.cpp)", 3,
    "Error in Kakadu File Format Support:\n",
    "Attempting to read or write a fragment list box which refers to one or more URL's, not found in the associated data references object (see `jpx_target::access_data_references').\0"
  },
  {
    "E(jpx.cpp)", 6,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source contains a malformed file type box.\0"
  },
  {
    "E(jpx.cpp)", 7,
    "Error in Kakadu File Format Support:\n",
    "Malformed reader requirements (rreq) box found in JPX data source.  Box terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 8,
    "Error in Kakadu File Format Support:\n",
    "Malformed reader requirements (rreq) box found in JPX data source.  Box terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 9,
    "Error in Kakadu File Format Support:\n",
    "Malformed reader requirements (rreq) box found in JPX data source. Box terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 10,
    "Error in Kakadu File Format Support:\n",
    "Malformed reader requirements (rreq) box found in JPX data source. Box terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 11,
    "Error in Kakadu File Format Support:\n",
    "Malformed reader requirements (rreq) box found in JPX data source.  Box appears to be too long.\0"
  },
  {
    "E(jpx.cpp)", 12,
    "Error in Kakadu File Format Support:\n",
    "Malformed Composition Options (copt) box found in JPX data source.  Insufficient or illegal field values encountered.  The height and width parameters must also be non-zero.\0"
  },
  {
    "E(jpx.cpp)", 13,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  Insufficient fields encountered.\0"
  },
  {
    "E(jpx.cpp)", 14,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box encountered in JPX data source.  Box appears to be too long.\0"
  },
  {
    "E(jpx.cpp)", 15,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  Terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 16,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  Terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 17,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  Terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 18,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  Terminated unexpectedly.\0"
  },
  {
    "E(jpx.cpp)", 19,
    "Error in Kakadu File Format Support:\n",
    "Illegal re-use count found in a compositing instruction within the JPX composition box.  The specified re-use counts found in the box lead to multiple conflicting definitions for the compositing layer which should be used by a particular instruction.\0"
  },
  {
    "E(jpx.cpp)", 31,
    "Error in Kakadu File Format Support:\n",
    "JPX data source appears to contain multiple JPX Codestream Registration (creg) boxes within the same compositing layer header (jplh) box.\0"
  },
  {
    "E(jpx.cpp)", 32,
    "Error in Kakadu File Format Support:\n",
    "Malformed Codestream Registration (creg) box found in JPX data source.  Insufficient or illegal fields encountered.\0"
  },
  {
    "E(jpx.cpp)", 33,
    "Error in Kakadu File Format Support:\n",
    "Malformed Codestream Registration (creg) box found in JPX data source.  Box size does not seem to be equal to 4+6k where k must be the number of referenced codestreams.\0"
  },
  {
    "E(jpx.cpp)", 34,
    "Error in Kakadu File Format Support:\n",
    "Malformed Codestream Registration (creg) box found in JPX data source.  Illegal (zero-valued) resolution parameters found for codestream .\0"
  },
  {
    "E(jpx.cpp)", 35,
    "Error in Kakadu File Format Support:\n",
    "Malformed Codestream Registration (creg) box found in JPX data source.  Alignment offsets must be strictly less than the denominator (point density) parameters, as explained in the JPX standard (accounting for corrigenda).\0"
  },
  {
    "E(jpx.cpp)", 37,
    "Error in Kakadu File Format Support:\n",
    "JPX source contains no image header box for a codestream.  The image header (ihdr) box cannot be found in a codestream header (chdr) box, and does not exist within a default JP2 header (jp2h) box.\0"
  },
  {
    "E(jpx.cpp)", 38,
    "Error in Kakadu File Format Support:\n",
    "JPX source contains a codestream with a palette (pclr) box, but no component mapping (cmap) box.  This illegal situation has been detected after examining both the codestream header (chdr) box, if any, for that codestream, and the default JP2 header (jp2h) box, if any.\0"
  },
  {
    "E(jpx.cpp)", 40,
    "Error in Kakadu File Format Support:\n",
    "Encountered a JPX compositing layer box which utilizes a non-existent codestream!\0"
  },
  {
    "E(jpx.cpp)", 41,
    "Error in Kakadu File Format Support:\n",
    "JP2/JPX source is internally inconsistent.  Either an explicit channel mapping box, or the set of channels implicitly identified by a colour space box, cannot all be associated with available code-stream image components.\0"
  },
  {
    "E(jpx.cpp)", 42,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source appears to contain more than one data reference (dtbl) box.  At most one should be found in the file.\0"
  },
  {
    "E(jpx.cpp)", 43,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source contains more than one top-level JP2 header (jp2h) box.\0"
  },
  {
    "E(jpx.cpp)", 45,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' does not commence with a valid JP2-family signature box.\0"
  },
  {
    "E(jpx.cpp)", 46,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' does not commence with a valid JP2-family signature box.\0"
  },
  {
    "E(jpx.cpp)", 47,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' does not contain a correctly positioned file-type (ftyp) box.\0"
  },
  {
    "E(jpx.cpp)", 48,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' does not contain a correctly positioned file-type (ftyp) box.\0"
  },
  {
    "E(jpx.cpp)", 49,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' contains a correctly positioned file-type box, but that box does not identify either JP2 or JPX as a compatible file type.\0"
  },
  {
    "E(jpx.cpp)", 50,
    "Error in Kakadu File Format Support:\n",
    "Data source supplied to `jpx_source::open' does not contain a correctly positioned reader requirements box.\0"
  },
  {
    "E(jpx.cpp)", 51,
    "Error in Kakadu File Format Support:\n",
    "JPX data source appears to contain no codestreams at all.\0"
  },
  {
    "E(jpx.cpp)", 17107201,
    "Error in Kakadu File Format Support:\n",
    "Attempting to convert a `jpx_metanode' entry in the metadata hierarchy into a link, whereas there are other nodes which are links and point to this node.  This is legal only if the converted node is to have the \"Grouping\" link-type and each of the existing linking nodes has \"Alternate-child\" link-type -- otherwise the representation within the JPX file format would require a cross-reference box to point to another cross-reference box.\0"
  },
  {
    "E(jpx.cpp)", 17107202,
    "Error in Kakadu File Format Support:\n",
    "Attempting to convert a `jpx_metanode' entry in the metadata hierarchy into a link to another node which is itself a link or other form of cross-reference box.  This is legal only if the target node has the \"Grouping\" link type and node being converted is being assigned an \"Alternate-child\" link type -- otherwise, the representation within the JPX file format would require a cross-reference box to point to another cross-reference box.\0"
  },
  {
    "E(jpx.cpp)", 17172737,
    "Error in Kakadu File Format Support:\n",
    "Trying to add a metadata link to a metadata node which itself is a link.  This is legal only if the target node has the \"Grouping\" link-type (then the cross-reference can refer to its containing `asoc' box) and then only if the link you are trying to add has the \"Alternate Child\" link type (otherwise the cross-reference cannot refer to the `asoc' box).\0"
  },
  {
    "E(jpx.cpp)", 17172739,
    "Error in Kakadu File Format Support:\n",
    "Attempting to convert a `jpx_metanode' entry in the metadata hierarchy into a link which points to itself.  This cannot be achieved legally, since a link node can be referenced by another link node only if the referenced node has the \"Grouping\" link-type and the referring node has the \"Alternate-child\" link-type.\0"
  },
  {
    "E(jpx.cpp)", 17240577,
    "Error in Kakadu File Format Support:\n",
    "You have defined one or more presentation tracks for a JPX container, added through `jpx_target::add_container', but at least one of these presentation tracks does not contain sufficient composition instructions to use all of the container's compositing layers that are assigned to the presentation track.  The resulting JPX file would not be compliant with AMD3 of IS15444-2.\0"
  },
  {
    "E(jpx.cpp)", 17306114,
    "Error in Kakadu File Format Support:\n",
    "Cumulative frame times for all compositing instructions that appear prior to a JPX container may not equal or exceed 2^32 milliseconds, since the LIFE-START field of the Compositing Layer Extensions Info box must be a 32-bit unsigned integer.\0"
  },
  {
    "E(jpx.cpp)", 33884418,
    "Error in Kakadu File Format Support:\n",
    "Trying to add descendants to a metadata node (`jpx_metanode') which is currently identified as a non-grouping link node.  Any link node (node represented by a cross-reference to another node in the metadata hierarchy) which has descendants must be a grouping link node -- one with link-type `JPX_GROUPING_LINK'.\0"
  },
  {
    "E(jpx.cpp)", 33884419,
    "Error in Kakadu File Format Support:\n",
    "Attempting to convert a `jpx_metanode' entry in the metadata hierarchy into a non-grouping link, where the node being converted already has descendants.  Link nodes which have descendants are automatically interpreted as grouping links.\0"
  },
  {
    "E(jpx.cpp)", 101192193,
    "Error in Kakadu File Format Support:\n",
    "Compositing Layer Extensions Info box identifies a frame count for its presentation tracks which is larger than the number of frames that can be synthesized using the compositing layers and compositing instructions recorded in its parent Compositing Layer Extensions box.\0"
  },
  {
    "E(jpx.cpp)", 285741569,
    "Error in Kakadu File Format Support:\n",
    "Number lists cannot record compositing layer or codestream indices greater than or equal to 2^24.\0"
  },
  {
    "E(jpx.cpp)", 285741573,
    "Error in Kakadu File Format Support:\n",
    "Atempting to move a metadata node across as a descendant of new metadata node that is embedded within a JPX container that is not compatible with the node to be moved or one of its descendants -- number list nodes may be embedded within JPX containers only if the compositing layers and/or codestreams that they reference are either top-level layers/codestreams or else layers/codestreams defined by the relevant container.\0"
  },
  {
    "E(jpx.cpp)", 369627651,
    "Error in Kakadu File Format Support:\n",
    "Trying to add descendants to a metadata node that has already been written to the output JPX file.\0"
  },
  {
    "E(jpx.cpp)", 369627652,
    "Error in Kakadu File Format Support:\n",
    "Trying to add metadata to a `jpx_target' object while an incomplete sequence of calls to `jpx_target::write_headers' or `jpx_target::write_metadata' is in progress.  You must continue to call such functions until they return NULL, before adding new content.\0"
  },
  {
    "E(jpx.cpp)", 369627654,
    "Error in Kakadu File Format Support:\n",
    "Trying to change a metadata node that has already been written to the output JPX file.\0"
  },
  {
    "E(jpx.cpp)", 369627655,
    "Error in Kakadu File Format Support:\n",
    "Trying to change metadata within a `jpx_target' object while an incomplete sequence of calls to `jpx_target::write_headers' or `jpx_target::write_metadata' is in progress.  You must continue to call such functions until they return NULL, before changing existing content.\0"
  },
  {
    "E(jpx.cpp)", 369627657,
    "Error in Kakadu File Format Support:\n",
    "Attempting to embed a new number list within a JPX container that has already been written to its output file.\0"
  },
  {
    "E(jpx.cpp)", 403116545,
    "Error in Kakadu File Format Support:\n",
    "Invalid J2CI (Multiple Codetream Info) box found while parsing JPX source -- each such box should hold two unsigned 32-bit integers: Ncs and Ltbl.\0"
  },
  {
    "E(jpx.cpp)", 419893761,
    "Error in Kakadu File Format Support:\n",
    "Multiple Codestream (J2CX) box appears malformed; embedded J2CI (info) sub-box advertises existence of sub-boxes that cannot be read.  This error could also arise if your data source does not support seeking.\0"
  },
  {
    "E(jpx.cpp)", 419893762,
    "Error in Kakadu File Format Support:\n",
    "Multiple Codestream (J2CX) box appears to have invalid J2CI info sub-box, advertising the fact that all sub-boxes refer to at most one codestream whereas at least one sub-box appears to refer to multiple codestreams.\0"
  },
  {
    "E(jpx.cpp)", 419893763,
    "Error in Kakadu File Format Support:\n",
    "Multiple Codestream (J2CX) box advertises more codestreams than can be found within its sub-boxes.\0"
  },
  {
    "E(jpx.cpp)", 419959297,
    "Error in Kakadu File Format Support:\n",
    "Trying to add a metadata link to an empty number list -- these will not be assigned a representation in a generated JPX file.\0"
  },
  {
    "E(jpx.cpp)", 419959298,
    "Error in Kakadu File Format Support:\n",
    "Trying to convert a `jpx_metanode' entry in the metadata hierarchy into a link to an empty number list -- these will not be assigned a representation in a generated JPX file.\0"
  },
  {
    "E(jpx.cpp)", 587665921,
    "Error in Kakadu File Format Support:\n",
    "Encountered Fragment Table (FTBL) box that does not contain a Fragment List sub-box.  File is invalid.\0"
  },
  {
    "E(jpx.cpp)", 587665922,
    "Error in Kakadu File Format Support:\n",
    "Top-level Contiguous Codestream boxes and Fragment Table boxes must all precede any Multiple Codestream boxes in a JPX file.\0"
  },
  {
    "E(jpx.cpp)", 587665923,
    "Error in Kakadu File Format Support:\n",
    "Top-level Codestream Header boxes must all precede any Compositing Layer Extensions boxes in a JPX file.\0"
  },
  {
    "E(jpx.cpp)", 587665924,
    "Error in Kakadu File Format Support:\n",
    "Top-level Compositing Layer Header boxes must all precede any Compositing Layer Extensions boxes in a JPX file.\0"
  },
  {
    "E(jpx.cpp)", 604443137,
    "Error in Kakadu File Format Support:\n",
    "At least one top-level Contiguous Codestream box or Fragment Table box must precede any Multiple Codestream box in a legal JPX file.\0"
  },
  {
    "E(jpx.cpp)", 604443138,
    "Error in Kakadu File Format Support:\n",
    "At least one top-level Compositing Layer box must precede any Compositing Layer Extensions box in a legal JPX file.\0"
  },
  {
    "E(jpx.cpp)", 604443139,
    "Error in Kakadu File Format Support:\n",
    "Top-level Composition box must precede any Compositing Layer Extensions box in a legal JPX file.\0"
  },
  {
    "E(jpx.cpp)", 604508673,
    "Error in Kakadu File Format Support:\n",
    "Looks like a top-level JPX compositing layer header box refers to a non-existent top-level codestream.  The file contains at least one codestream header box, but not enough of them to accommodate the referenced codestreams.\0"
  },
  {
    "E(jpx.cpp)", 604508674,
    "Error in Kakadu File Format Support:\n",
    "Looks like a top-level JPX Compositing Layer Header box refers to a non-existent top-level codestream; top-level Codestream Header boxes must all appear before Compositing Layer Extensions boxes.\0"
  },
  {
    "E(jpx.cpp)", 621220353,
    "Error in Kakadu File Format Support:\n",
    "Error in Compositing Layer Extensions Info box: box appears to be prematurely trunctated.\0"
  },
  {
    "E(jpx.cpp)", 621220355,
    "Error in Kakadu File Format Support:\n",
    "A Compositing Layer Extensions box that specifies indefinite repetition (Mjclx=0) should not be followed by further Compositing Layer Extensions boxes.\0"
  },
  {
    "E(jpx.cpp)", 621220356,
    "Error in Kakadu File Format Support:\n",
    "Error in Compositing Layer Extensions Info box: the number of base compositing layers must be non-zero.\0"
  },
  {
    "E(jpx.cpp)", 621220357,
    "Error in Kakadu File Format Support:\n",
    "Error in Compositing Layer Extensions Info box: the number of presentation threads (or tracks) is declared as zero, yet the number of presentation frames is declared non-zero.\0"
  },
  {
    "E(jpx.cpp)", 621220359,
    "Error in Kakadu File Format Support:\n",
    "Error in Compositing Layer Extensions Info box: indefinite repetition (Mjclx=0) is allowed only for boxes that provide at least one new Codestream Header (Cjclx > 0).\0"
  },
  {
    "E(jpx.cpp)", 621220360,
    "Error in Kakadu File Format Support:\n",
    "Expected a JP2 Header box to complete the descriptive metadata (e.g., dimensions, component map, etc.) for a codestream that does not have all this information.  The file appears to be invalid.\0"
  },
  {
    "E(jpx.cpp)", 621220361,
    "Error in Kakadu File Format Support:\n",
    "Expected a JP2 Header box to complete the descriptive metadata (e.g., colour, channel bindings, etc.) for a compositing layer that does not have all this information.  The file appears to be invalid.\0"
  },
  {
    "E(jpx.cpp)", 621220362,
    "Error in Kakadu File Format Support:\n",
    "At least one top-level Codestream Header box must precede any Compositing Layer Extensions box in a legal JPX file.\0"
  },
  {
    "E(jpx.cpp)", 621220363,
    "Error in Kakadu File Format Support:\n",
    "JPX source does not contain any Contiguous Codestream or Fragment Table box, either at the top level or within a Multiple Codestream box, for the logical codestream with (zero based) index \0"
  },
  {
    "E(jpx.cpp)", 621220369,
    "Error in Kakadu File Format Support:\n",
    "Invalid repetition index used to map codestream or compositing layer indices for a JPX container (Compositing Layer Extensions box).  Problem most likely caused by corruption of a `jpx_codestream_source' or `jpx_layer_source' interface object.\0"
  },
  {
    "E(jpx.cpp)", 621220370,
    "Error in Kakadu File Format Support:\n",
    "JPX container (Compositing Layer Extensions box) has embedded compositing layer without any CREG box to bind it to a codestream; moreover the implicit binding rule associates some, but not all of the compositing layers with top-level codestreams.  To avoid such illegal situations, it is best to use Codestream Registration boxes within JPX containers.\0"
  },
  {
    "E(jpx.cpp)", 621220371,
    "Error in Kakadu File Format Support:\n",
    "Indefinitely repeated JPX container (Compositing Layer Extensions box) has embedded compositing layer without any CREG box to bind it to a codestream; moreover the implicit binding rule associates at least some of the indefinitely repeated layers with top-level codestreams; there is no way to guarantee that the others will also be top-level.  At the very least, this is a violation of the intent behind indefinitely repeated JCLX boxes.\0"
  },
  {
    "E(jpx.cpp)", 621220372,
    "Error in Kakadu File Format Support:\n",
    "JPX container (Compositing Layer Extensions box) has embedded compositing layer without any CREG box to bind it to a codestream; moreover, the implicit binding rule associates it with a codestream that appears to belong to a different JPX container.  Container-defined codestreams can only be used by the container's own compositing layers.\0"
  },
  {
    "E(jpx.cpp)", 621220373,
    "Error in Kakadu File Format Support:\n",
    "JPX container (Compositing Layer Extensions box) has embedded compositing layer without any CREG box to bind it to a codestream; moreover the implicit binding rule associates it with a codestream that is defined within the same container.  In this situation, the container must either not be repeated, or else the implicit binding rule must yield consistent associations on each repetition.  This is not the case; it is best to use Codestream Registration boxes within JPX containers.\0"
  },
  {
    "E(jpx.cpp)", 637669633,
    "Error in Kakadu File Format Support:\n",
    "Malformed Instruction Set (inst) box found in JPX data source.  ROT parameter must either be 0 or else take values in the range 1 to 4 or 17 to 20.\0"
  },
  {
    "E(jpx.cpp)", 637997575,
    "Error in Kakadu File Format Support:\n",
    "Too many Codestream headers found inside Compositing Layer Extensions box, given count advertised in itsJCLI (INFO) sub-box.\0"
  },
  {
    "E(jpx.cpp)", 637997576,
    "Error in Kakadu File Format Support:\n",
    "Too many Compositing Layer headers found inside Compositing Layer Extensions box, given count advertised by its JCLI (INFO) sub-box.\0"
  },
  {
    "E(jpx.cpp)", 637997577,
    "Error in Kakadu File Format Support:\n",
    "Insufficient Codestream or Compositing Layer header boxes found inside Compositing Layer Extensions box, given the counts advertised by its JCLI (INFO) sub-box.\0"
  },
  {
    "E(jpx.cpp)", 688329217,
    "Error in Kakadu File Format Support:\n",
    "Number of distinct collections of Instruction Set boxes found in Compositing Layer Extensions box does not agree with the number of presentation threads (or tracks) advertised by the JCLI (INFO) sub-box.\0"
  },
  {
    "E(jpx.cpp)", 805769729,
    "Error in Kakadu File Format Support:\n",
    "The Instruction Set boxes that define a Presentation Track (or thread) within a Compositing Layer Extensions box must appear one after the other, without any other boxes in between.\0"
  },
  {
    "E(jpx.cpp)", 805769730,
    "Error in Kakadu File Format Support:\n",
    "Number of groups of Instruction Set boxes encountered within a Compositing Layer Extensions box exceeds the number of presentation tracks (or threads) advertised by its INFO sub-box.\0"
  },
  {
    "E(jpx.cpp)", 822546946,
    "Error in Kakadu File Format Support:\n",
    "Invalid Composition Options box encountered in JPX file -- height and width parameters must both be non-zero.\0"
  },
  {
    "E(jpx.cpp)", 822546947,
    "Error in Kakadu File Format Support:\n",
    "Inconsistency detected between frame count recorded in Compositing Layer Extensions Info box and the number of frames that can actually be formed from the compositing instructions found within the Compositing Layer Extensions box.\0"
  },
  {
    "E(jpx.cpp)", 1349591056,
    "Error in Kakadu File Format Support:\n",
    "Invalid relative \0"
    " found inside Codesteam Registration or Number List box, within a JPX container (Compositing Layer Extensions box).  All such indices must either identify top-level image entities or else one of the base entities defined by the container, expressed relative to a hypothetical file in which top-level entities are immediately followed by the container in question.  The offending relative index is \0"
  },
  {
    "W(jpx.cpp)", 0,
    "Warning in Kakadu File Format Support:\n",
    "JPX data source appears to contain multiple composition boxes!! This is illegal.  All but first will be ignored.\0"
  },
  {
    "W(jpx.cpp)", 8400897,
    "Warning in Kakadu File Format Support:\n",
    "Malformed oriented elliptical region refinement information found in ROI Descriptions (`roid') box in JPX data source.  Oriented ellipses require two consecutive regions, the first of which is a simple ellipse, while the second has a centre which lies within (but not on) the bounding rectangle associated with the first ellipse.\0"
  },
  {
    "W(jpx.cpp)", 17306113,
    "Warning in Kakadu File Format Support:\n",
    "Problem interpreting compositing instructions found within a Composition box or Compositing Layer Extensions box.  The instructions in question may be legal but describe an endless repetition of frames, each of which renders exactly the same content!  This will cause problems for the internal implementation, so the repetition information is being modified -- this may produce an incomplete or incorrectly interpreted animation.\0"
  },
  {
    "W(jpx.cpp)", 84217857,
    "Warning in Kakadu File Format Support:\n",
    "Unable to completely fill the region bounded by the scribble path; this is probably an internal flaw; you could either fill the unfilled portion manually or try again with a different complexity setting.\0"
  },
  {
    "W(jpx.cpp)", 151064577,
    "Warning in Kakadu File Format Support:\n",
    "Malformed quadrilateral region of interest information found in ROI Descriptions (`roid') box in JPX data source.  Generic quadrilaterals require two consecutive, regions, the first of which is a simple rectangle, while the second identifies a second rectangular region, contained within the first.\0"
  },
  {
    "W(jpx.cpp)", 151195649,
    "Warning in Kakadu File Format Support:\n",
    "ROI shape edit will cause the maximum number of regions in the JPX ROI Description box to be exceeded.  Delete or simplify some regions to simple rectangles or ellipses.\0"
  },
  {
    "W(jpx.cpp)", 285282305,
    "Warning in Kakadu File Format Support:\n",
    "Illegal quadrilateral vertices encountered while reading an ROI Description (`roid') box from a JPX source.  Quadrilateral edges cross through each other!\0"
  },
  {
    "W(jpx.cpp)", 285282306,
    "Warning in Kakadu File Format Support:\n",
    "Cannot write all component regions to a single containing ROI Description (`roid') description box.  The JPX file format imposes a limit of 255 individual regions, but note that general quadrilaterals and oriented ellipses each consume 2 regions from this limit.\0"
  },
  {
    "W(jpx.cpp)", 419694849,
    "Warning in Kakadu File Format Support:\n",
    "Malformed Cross Reference (`cref') box found in JPX data source.\0"
  },
  {
    "W(jpx.cpp)", 621220354,
    "Warning in Kakadu File Format Support:\n",
    "Compositing Layer Extensions Info box contains one or more ridiculously large parameters!!  Values are being truncated; memory allocation faults may also arise.\0"
  },
  {
    "W(jpx.cpp)", 638584833,
    "Warning in Kakadu File Format Support:\n",
    "Malformed Number List (`nlst') box found in JPX data source.  Box body does not contain a whole number of 32-bit integers.\0"
  },
  {
    "W(jpx.cpp)", 638584834,
    "Warning in Kakadu File Format Support:\n",
    "Malformed ROI Descriptions (`roid') box encountered in JPX data source.\0"
  },
  {
    "W(jpx.cpp)", 822546945,
    "Warning in Kakadu File Format Support:\n",
    "Composition Options box supplies composition dimensions that are too large to be properly represented internally by Kakadu!  Values are being truncated; unexpected rendering artefacts may result.\0"
  }
};

static bool dummy_val = kdl_register_text(data,103);

#ifndef KDU_EXCLUDE_DEVELOPER_TEXT

static kdl_message_info dev_data[69] = {
  {
    "E(jpx.cpp)", 2,
    "Error in Kakadu File Format Support:\n",
    "Trying to write too many fragments to a fragment list (flst) box.  Maximum number of fragments is 65535, but note that each written fragment must have a length < 2^32 bytes.  Very long fragments may thus need to be split, creating the appearance of a very large number of fragments.\0"
  },
  {
    "E(jpx.cpp)", 4,
    "Error in Kakadu File Format Support:\n",
    "Attempting to call `jpx_input_box::open_as' without first closing the box.\0"
  },
  {
    "E(jpx.cpp)", 5,
    "Error in Kakadu File Format Support:\n",
    "You must supply a non-NULL `ultimate_src' argument to `jpx_input_box::open_as'.\0"
  },
  {
    "E(jpx.cpp)", 20,
    "Error in Kakadu File Format Support:\n",
    "You must add at least one compositing instruction to every frame created using `jpx_composition::add_frame'.\0"
  },
  {
    "E(jpx.cpp)", 22,
    "Error in Kakadu File Format Support:\n",
    "Illegal loop count supplied to `jpx_composition::set_loop_count'.  Legal values must be in the range 0 (indefinite looping) to 255 (max explicit repetitions).\0"
  },
  {
    "E(jpx.cpp)", 30,
    "Error in Kakadu File Format Support:\n",
    "You may not use `jpx_meta_manager::insert_node' to insert a region-specific metadata node which is not also associated with at least one codestream.  The reason is that ROI description boxes have meaning only when associated with codestreams, as described in the JPX standard.\0"
  },
  {
    "E(jpx.cpp)", 36,
    "Error in Kakadu File Format Support:\n",
    "One or more codestreams registration parameters supplied using `jpx_layer_target::set_codestream_registration' cannot be recorded in a legal JPX Codestream Registration (creg) box.\0"
  },
  {
    "E(jpx.cpp)", 39,
    "Error in Kakadu File Format Support:\n",
    "Attempting to use `jpx_codestream_source::open_stream' a second time, to gain access to the same codestream, without first closing the box.  To maintain multiple open instances of the same codestream, you should supply your own `jpx_input_box' object, rather than attempting to use the internal resource multiple times concurrently.\0"
  },
  {
    "E(jpx.cpp)", 44,
    "Error in Kakadu File Format Support:\n",
    "Attempting invoke `jpx_source::open' on a JPX source object which has been completely opened, but not yet closed.\0"
  },
  {
    "E(jpx.cpp)", 53,
    "Error in Kakadu File Format Support:\n",
    "You may not call `jpx_codestream_target::open_stream' or `jpx_codestream_target::write_fragment_table' until after the JPX file header has been written using `jpx_target::write_headers'.\0"
  },
  {
    "E(jpx.cpp)", 55,
    "Error in Kakadu File Format Support:\n",
    "You must not call `jpx_codestream_target::write_fragment_table' without first adding one or more references to codestream fragments.\0"
  },
  {
    "E(jpx.cpp)", 56,
    "Error in Kakadu File Format Support:\n",
    "You may not call `jpx_codestream_target::open_stream' or `jpx_codestream_target::write_fragment_table' until after the JPX file header has been written using `jpx_target::write_headers'.\0"
  },
  {
    "E(jpx.cpp)", 57,
    "Error in Kakadu File Format Support:\n",
    "You may not call `open_stream' on a `jpx_codestream_target' object to which one or more codestream fragment references have already been added.\0"
  },
  {
    "E(jpx.cpp)", 59,
    "Error in Kakadu File Format Support:\n",
    "The `jpx_layer_target::add_colour' function has been used to add multiple colour descriptions for a JPX compositing layer, but not all colour descriptions have the same number of colour channels.\0"
  },
  {
    "E(jpx.cpp)", 60,
    "Error in Kakadu File Format Support:\n",
    "Application has configured a JPX compositing layer box which utilizes a non-existent codestream!\0"
  },
  {
    "E(jpx.cpp)", 61,
    "Error in Kakadu File Format Support:\n",
    "Invalid `precedence' or `approx' parameter supplied to `jpx_layer_target::add_colour'.  Legal values for the precedence parameter must lie in the range -128 to +127, while legal values for the approximation level parameter are 0, 1, 2, 3 and 4.\0"
  },
  {
    "E(jpx.cpp)", 62,
    "Error in Kakadu File Format Support:\n",
    "The denominator values supplied via all calls to `jpx_layer_target::set_codestream_registration' within the same compositing layer must be identical.  This is because the codestream registration (creg) box can record only one denominator (point density) to be shared by all the codestream sampling and alignment parameters.\0"
  },
  {
    "E(jpx.cpp)", 63,
    "Error in Kakadu File Format Support:\n",
    "Illegal alignment or sampling parameters passed to `jpx_layer_target::set_codestream_registration'.  The alignment offset and sampling numerator values must be non-negative (non-zero for sampling factors) and no larger than 255; moreover, the alignment offsets must be strictly less than the denominator (point density) values and the common sampling denominator must lie be in the range 1 to 65535.\0"
  },
  {
    "E(jpx.cpp)", 64,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a new top-level box within a JPX file, while another top-level box is already open!\0"
  },
  {
    "E(jpx.cpp)", 65,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jpx_target' object which is already opened for writing a JPX file.\0"
  },
  {
    "E(jpx.cpp)", 66,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write a JPX file which has no top-level code-stream, or no top-level compositing layer.\0"
  },
  {
    "E(jpx.cpp)", 17172738,
    "Error in Kakadu File Format Support:\n",
    "Trying to convert a metadata node into a link which points to another metadata node that appears to have been deleted.\0"
  },
  {
    "E(jpx.cpp)", 17240578,
    "Error in Kakadu File Format Support:\n",
    "Addition of top-level compositing layers to a JPX file via `jpx_target::add_layer' must cease after the first call to `jpx_target::write_headers' or `jpx_target::add_container'.\0"
  },
  {
    "E(jpx.cpp)", 17240579,
    "Error in Kakadu File Format Support:\n",
    "Addition of top-level codestreams to a JPX file via `jpx_target::add_codestream' must cease after the first call to `jpx_target::write_headers' or `jpx_target::add_container'.\0"
  },
  {
    "E(jpx.cpp)", 17240583,
    "Error in Kakadu File Format Support:\n",
    "In order to retain the right to add JPX containers after the first call to `jpx_target::write_headers' or `jpx_target::write_metadata', you must add at least one container or invoke `jpx_target::expect_containers' before that first call.\0"
  },
  {
    "E(jpx.cpp)", 17371649,
    "Error in Kakadu File Format Support:\n",
    "The first call to `jpx_target::expect_containers' or `jpx_target::add_container' must appear before the first call to `jpx_target::write_headers' or `jpx_target::write_metadata'.\0"
  },
  {
    "E(jpx.cpp)", 33884417,
    "Error in Kakadu File Format Support:\n",
    "Trying to add new metadata to a `jpx_metanode' interface which is empty!\0"
  },
  {
    "E(jpx.cpp)", 34017793,
    "Error in Kakadu File Format Support:\n",
    "Attempting to add presentation tracks to a JPX container that has already been finalized -- has probably already been written to the file!\0"
  },
  {
    "E(jpx.cpp)", 34017794,
    "Error in Kakadu File Format Support:\n",
    "Invalid number of track layers passed to `jpx_container_target::add_presentation_track'.  The total number of layers for all presentation tracks in a JPX container must not exceed the number of base compositing layers defined for the container.\0"
  },
  {
    "E(jpx.cpp)", 34017795,
    "Error in Kakadu File Format Support:\n",
    "Attempting to add frames to a JPX composition after the composition has been finalized for writing.\0"
  },
  {
    "E(jpx.cpp)", 34017796,
    "Error in Kakadu File Format Support:\n",
    "Attempting to add instructions to a JPX composition after the composition has been finalized for writing.\0"
  },
  {
    "E(jpx.cpp)", 34017797,
    "Error in Kakadu File Format Support:\n",
    "All presentation tracks added to a JPX container must have exactly the same total number of frames.\0"
  },
  {
    "E(jpx.cpp)", 34017798,
    "Error in Kakadu File Format Support:\n",
    "Use of inaccessible codestream from within a compositing layer!  You may be receiving this error because a top-level compositing layer has referenced a non-existent codestream or one that is not found at the top-level of the file.  You may also be receiving this error because a compositing layer found within a JPX container has referenced a codestream that lies neither at the top-level of the file nor within the same container.\0"
  },
  {
    "E(jpx.cpp)", 50795009,
    "Error in Kakadu File Format Support:\n",
    "A JPX container must either have a fixed number of repetitions or be the last one in the file; you are attempting to add another container after one for which the number of repetitions was supplied as 0 (indefinite).\0"
  },
  {
    "E(jpx.cpp)", 50795010,
    "Error in Kakadu File Format Support:\n",
    "A JPX container for which the number of repetitions is not fixed (zero repetition factor supplied) must have at least one codestream header box (non-zero `num_base_codestreams' value).\0"
  },
  {
    "E(jpx.cpp)", 50795011,
    "Error in Kakadu File Format Support:\n",
    "JPX containers must have at least one compositing layer header box.\0"
  },
  {
    "E(jpx.cpp)", 50795012,
    "Error in Kakadu File Format Support:\n",
    "Too many calls to `jpx_codestream_target::write_fragment_table' for a given codestream header instance.\0"
  },
  {
    "E(jpx.cpp)", 50795013,
    "Error in Kakadu File Format Support:\n",
    "Too many calls to `jpx_codestream_target::open_stream' for a given codestream header instance.\0"
  },
  {
    "E(jpx.cpp)", 50795014,
    "Error in Kakadu File Format Support:\n",
    "You may not call `open_stream' on a `jpx_codestream_target' object before closing any existing open box obtained via a previous call to `open_stream'.\0"
  },
  {
    "E(jpx.cpp)", 50795015,
    "Error in Kakadu File Format Support:\n",
    "You may not call `write_fragment_table' on a `jpx_codestream_target' object before closing any existing open box obtained via a previous call to `open_stream'.\0"
  },
  {
    "E(jpx.cpp)", 50795017,
    "Error in Kakadu File Format Support:\n",
    "You appear to be generating contiguous codestreams or fragment tables out of order for codestreams that are described within a JPX container.\0"
  },
  {
    "E(jpx.cpp)", 83955713,
    "Error in Kakadu File Format Support:\n",
    "Registration information has been supplied via the `jpx_layer_target::set_codestream_registration' for a codestream which is not used by any channel defined for the compositing layer in question!  The codestream in question has (zero-based) index \0"
    " and the compositing layer has (zero-based) index \0"
  },
  {
    "E(jpx.cpp)", 84480513,
    "Error in Kakadu File Format Support:\n",
    "Attempt to read from a JP2 box which is either not open or has an open sub-box.\0"
  },
  {
    "E(jpx.cpp)", 117903873,
    "Error in Kakadu File Format Support:\n",
    "You must add at least one top-level compositing layer and one top-level codestream to a `jpx_target' object before invoking its `add_container' function.\0"
  },
  {
    "E(jpx.cpp)", 117903875,
    "Error in Kakadu File Format Support:\n",
    "JPX containers may not be written to a file that contains no top-level composition box.  You need to add at least one top-level composition frame.\0"
  },
  {
    "E(jpx.cpp)", 134681089,
    "Error in Kakadu File Format Support:\n",
    "Presentation track added to JPX container has no compositing instructions defined!  Tracks are delineated within their containers by one or more compositing instructions.\0"
  },
  {
    "E(jpx.cpp)", 268964353,
    "Error in Kakadu File Format Support:\n",
    "Attempting to embed a new number list within a JPX container via `jpx_metanode::add_numlist' -- this is only allowed for number lists that will appear at the top level of the metadata hierarchy.\0"
  },
  {
    "E(jpx.cpp)", 268964354,
    "Error in Kakadu File Format Support:\n",
    "Attempting to embed a new number list within a JPX container which either does not exist or is not compatible with the compositing layer and/or codestream indices to be recorded in the number list.\0"
  },
  {
    "E(jpx.cpp)", 285741571,
    "Error in Kakadu File Format Support:\n",
    "Attempting to create a container-embedded number list with one or more codestream or compositing layer indices that do not belong to the relevant JPX container.\0"
  },
  {
    "E(jpx.cpp)", 285741572,
    "Error in Kakadu File Format Support:\n",
    "`jpx_metanode::change_parent' may not be used to move a metanode to an empty interface or between the metadata hierarchies managed by different objects.\0"
  },
  {
    "E(jpx.cpp)", 302518785,
    "Error in Kakadu File Format Support:\n",
    "The `jpx_meta_manager::insert_node' function may be passed a non-negative `container_id' argument only if the node is to be inserted as an immediate descendant of the root of the metadata hierarchy, or if the node is to be inserted beneath an existing `root' node that is already embedded within the same JPX container.\0"
  },
  {
    "E(jpx.cpp)", 302518786,
    "Error in Kakadu File Format Support:\n",
    "`container_id' passed to `jpx_meta_manager::insert_node' does not correspond to an existing JPX container.\0"
  },
  {
    "E(jpx.cpp)", 302518787,
    "Error in Kakadu File Format Support:\n",
    "Attempting to use `jpx_meta_manager::insert_node' to create a number list that is embedded within an incompatible JPX container, either explicitly (via `container_id' >= 0) or implicitly (via a non-empty `root' metanode that is itself embedded within a JPX container).  Compatibility means that the supplied compositing layer and codestream indices must must correspond to compositing layers or codestreams that are defined either at the top level of the file or by the JPX container.\0"
  },
  {
    "E(jpx.cpp)", 369562113,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a new top-level box or a new code-stream, while another contiguous code-stream box is still open.  After a call to `jpx_codestream_target::open_stream', you must be sure to finish writing the code-stream and close the box, before attempting to open another one, close the `jpx_target' object or invoke its `write_headers' or `write_metadata' function.\0"
  },
  {
    "E(jpx.cpp)", 369627649,
    "Error in Kakadu File Format Support:\n",
    "Calling `jpx_target::write_headers' before completing an outstanding sequence of calls to `jpx_target::write_metadata'.  You must call each of these functions until they return NULL before calling the other.\0"
  },
  {
    "E(jpx.cpp)", 369627650,
    "Error in Kakadu File Format Support:\n",
    "Calling `jpx_target::write_metadata' before completing an outstanding sequence of calls to `jpx_target::write_headers'.  You must call each of these functions until they return NULL before calling the other.\0"
  },
  {
    "E(jpx.cpp)", 369627653,
    "Error in Kakadu File Format Support:\n",
    "Trying to change metadata via a `jpx_metanode' interface which is empty!\0"
  },
  {
    "E(jpx.cpp)", 369627664,
    "Error in Kakadu File Format Support:\n",
    "Attempting to add a metadata link (cross reference box) to a metanode that has already been written and has not been marked for target address preservation.  You can fix this by calling `jpx_metanode::preserve_for_links'.\0"
  },
  {
    "E(jpx.cpp)", 369627665,
    "Error in Kakadu File Format Support:\n",
    "Attempting to create a link (cross reference box) to a metanode that has already been written and has not been marked for target address preservation.  You can fix this by calling `jpx_metanode::preserve_for_links'.\0"
  },
  {
    "E(jpx.cpp)", 386404865,
    "Error in Kakadu File Format Support:\n",
    "Call to `jpx_metanode::preserve_links' is too late -- the node has already been deleted or written to the file!\0"
  },
  {
    "E(jpx.cpp)", 402788353,
    "Error in Kakadu File Format Support:\n",
    "Invalid set of ROI regions supplied to `jpx_roi_editor::init'.\0"
  },
  {
    "E(jpx.cpp)", 553912577,
    "Error in Kakadu File Format Support:\n",
    "Trying to add a metadata link to a metadata node which appears to have been deleted.\0"
  },
  {
    "E(jpx.cpp)", 570888705,
    "Error in Kakadu File Format Support:\n",
    "The URL index passed to `jpx_fragment_list::add_fragment' must lie in the range 0 to 65535.\0"
  },
  {
    "E(jpx.cpp)", 587665925,
    "Error in Kakadu File Format Support:\n",
    "You must supply a non-empty fragment list in calls to `jpx_input_box::open_as'.\0"
  },
  {
    "E(jpx.cpp)", 621220358,
    "Error in Kakadu File Format Support:\n",
    "Unable to allocate sufficient memory to record even the base compositing layers or codestreams associated with Compositing Layer Extensions box.  The box must be ridiculously large and unwieldly.\0"
  },
  {
    "W(jpx.cpp)", 2,
    "Warning in Kakadu File Format Support:\n",
    "Started writing a JPX file, but failed to write all top-level codestreams before calling `jpx_target::close'.\0"
  },
  {
    "W(jpx.cpp)", 3,
    "Warning in Kakadu File Format Support:\n",
    "Started writing JPX file headers, but failed to finish initiated sequence of calls to `jpx_target::write_headers'.  Problem is most likely due to the use of `jpx_codestream_target::set_breakpoint' or `jpx_layer_target::set_breakpoint' and failure to handle the breakpoints via multiple calls to `jpx_target::write_headers'.\0"
  },
  {
    "W(jpx.cpp)", 4,
    "Warning in Kakadu File Format Support:\n",
    "Failed to catch all breakpoints installed via `jpx_codestream_target::set_breakpoint' or `jpx_layer_target::set_breakpoint'.  All required compositing layer header boxes and codestream header boxes have been automatically written while closing the file, but some of these included application-installed breakpoints where the application would ordinarily have written its own extra boxes.  This suggests that the application has failed to make sufficient explicit calls to `jpx_target::write_headers'.\0"
  },
  {
    "W(jpx.cpp)", 50795016,
    "Warning in Kakadu File Format Support:\n",
    "Started writing a JPX file, but failed to complete the writing of all JPX containers and/or all of their associated codestreams.\0"
  }
};

static bool dev_dummy_val = kdl_register_text(dev_data,69);

#endif // !KDU_EXCLUDE_DEVELOPER_TEXT
