// This file has been automatically generated by "kdu_hyperdoc"
// Do not edit manually.
// Copyright 2001, David Taubman, The University of New South Wales (UNSW)
#include "kdu_aux.h"

/* ============================================ */
// Special classes for use in binding callbacks
/* ============================================ */

//---------------------------------------------------
// Derived version of class: kdu_cache
_aux_extended__kdu_cache::_aux_extended__kdu_cache()
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_client_notifier
_aux_extended__kdu_client_notifier::_aux_extended__kdu_client_notifier()
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_compressed_source_nonnative
_aux_extended__kdu_compressed_source_nonnative::_aux_extended__kdu_compressed_source_nonnative()
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_compressed_target_nonnative
_aux_extended__kdu_compressed_target_nonnative::_aux_extended__kdu_compressed_target_nonnative()
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_message
_aux_extended__kdu_message::_aux_extended__kdu_message()
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_region_compositor
_aux_extended__kdu_region_compositor::_aux_extended__kdu_region_compositor(kdu_thread_env *env, kdu_thread_queue *env_queue)
    : kdu_region_compositor(env,env_queue)
{
  this->_delegator = NULL;
}
_aux_extended__kdu_region_compositor::_aux_extended__kdu_region_compositor(kdu_compressed_source *source, int persistent_cache_threshold)
    : kdu_region_compositor(source,persistent_cache_threshold)
{
  this->_delegator = NULL;
}
_aux_extended__kdu_region_compositor::_aux_extended__kdu_region_compositor(jpx_source *source, int persistent_cache_threshold)
    : kdu_region_compositor(source,persistent_cache_threshold)
{
  this->_delegator = NULL;
}
_aux_extended__kdu_region_compositor::_aux_extended__kdu_region_compositor(mj2_source *source, int persistent_cache_threshold)
    : kdu_region_compositor(source,persistent_cache_threshold)
{
  this->_delegator = NULL;
}

//---------------------------------------------------
// Derived version of class: kdu_thread_safe_message
_aux_extended__kdu_thread_safe_message::_aux_extended__kdu_thread_safe_message()
{
  this->_delegator = NULL;
}

