// -----------------------------------------------------------------
// This file is automatically generated by "kdu_text_extractor"
// Do not edit the file directly.  You may, however, use this file
// as a template for alternate versions in which the text strings
// are translated into different languages.
// -----------------------------------------------------------------
#include <kdu_messaging.h>

struct kdl_message_info{
  const char *context;
  kdu_uint32 id;
  const char *lead_in;
  const char *text;
};

static bool
  kdl_register_text(kdl_message_info *info, int num_records)
{
  for (; num_records > 0; num_records--, info++)
    kdu_customize_text(info->context,info->id,
                       info->lead_in,info->text);
  return true;
}

static kdl_message_info data[78] = {
  {
    "E(jp2.cpp)", 1,
    "Error in Kakadu File Format Support:\n",
    "Unable to open input file\0"
  },
  {
    "E(jp2.cpp)", 5,
    "Error in Kakadu File Format Support:\n",
    "Illegal placeholder box encountered.  Placeholders must not use the extended length field and must have a length of at least 28 bytes!\0"
  },
  {
    "E(jp2.cpp)", 6,
    "Error in Kakadu File Format Support:\n",
    "Illegal box length field encountered in JP2 file.\0"
  },
  {
    "E(jp2.cpp)", 7,
    "Error in Kakadu File Format Support:\n",
    "Illegal box length field encountered in JP2 file.\0"
  },
  {
    "E(jp2.cpp)", 8,
    "Error in Kakadu File Format Support:\n",
    "Illegal box length field encountered in stream equivalent box header embedded within a JP2 placeholder box.\0"
  },
  {
    "E(jp2.cpp)", 12,
    "Error in Kakadu File Format Support:\n",
    "Unable to dereference file offset in the `jp2_locator' object supplied to `jp2_input_box::open'.  The server is deliberately preventing access to the original box in which the file offset resides.\0"
  },
  {
    "E(jp2.cpp)", 13,
    "Error in Kakadu File Format Support:\n",
    "Unable to open the box identified by the `jp2_locator' object supplied to `jp2_input_box::open'.  The server is deliberately preventing access to the box or any stream equivalent.\0"
  },
  {
    "E(jp2.cpp)", 22,
    "Error in Kakadu File Format Support:\n",
    "Cached data-bin appears to be complete yet terminates prior to the end of the current JP2 box.\0"
  },
  {
    "E(jp2.cpp)", 26,
    "Error in Kakadu File Format Support:\n",
    "Unable to open output file\0"
  },
  {
    "E(jp2.cpp)", 43,
    "Error in Kakadu File Format Support:\n",
    "Malformed image header box (ihdr) found in JP2-family data source.  Not all fields were present.\0"
  },
  {
    "E(jp2.cpp)", 44,
    "Error in Kakadu File Format Support:\n",
    "Malformed image header box (ihdr) found in JP2-family data source.  The box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 45,
    "Error in Kakadu File Format Support:\n",
    "Malformed image header box (ihdr) found in JP2-family data source.  The box contains fields which do not conform to their legal range.\0"
  },
  {
    "E(jp2.cpp)", 46,
    "Error in Kakadu File Format Support:\n",
    "Sorry: Cannot process JP2-family data sources whose image header box contains height or width values larger than 2^{31}-1.\0"
  },
  {
    "E(jp2.cpp)", 47,
    "Error in Kakadu File Format Support:\n",
    "Malformed bits per component (bpcc) box found in JP2-family data source.  The box contains insufficient bit-depth specifiers.\0"
  },
  {
    "E(jp2.cpp)", 48,
    "Error in Kakadu File Format Support:\n",
    "Malformed bits per component (bpcc) box found in JP2-family data source.  The box contains an illegal bit-depth specifier.  Bit depths may not exceed 38 bits per sample.\0"
  },
  {
    "E(jp2.cpp)", 49,
    "Error in Kakadu File Format Support:\n",
    "Malformed bits per component (bpcc) box found in JP2-family data source.  The box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 57,
    "Error in Kakadu File Format Support:\n",
    "Malformed palette (pclr) box found in JP2-family data source.  Insufficient or illegal fields encountered.\0"
  },
  {
    "E(jp2.cpp)", 58,
    "Error in Kakadu File Format Support:\n",
    "Malformed palette (pclr) box found in JP2-family data source.  The box contains insufficient bit-depth specifiers.\0"
  },
  {
    "E(jp2.cpp)", 59,
    "Error in Kakadu File Format Support:\n",
    "Malformed palette (pclr) box found in JP2-family data. source.  The box contains an illegal bit-depth specifier.  Bit depths may not exceed 38 bits per sample.\0"
  },
  {
    "E(jp2.cpp)", 60,
    "Error in Kakadu File Format Support:\n",
    "Malformed palette (pclr) box found in JP2-family data source.  The box contains insufficient palette entries.\0"
  },
  {
    "E(jp2.cpp)", 61,
    "Error in Kakadu File Format Support:\n",
    "Malformed palette (pclr) box encountered in JP2-family data source.  Box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 66,
    "Error in Kakadu File Format Support:\n",
    "Malformed component mapping (cmap) box encountered in JP2-family data source.  The body of any such box must contain exactly four bytes for each cmap-channel and there must be at least one cmap-channel.\0"
  },
  {
    "E(jp2.cpp)", 67,
    "Error in Kakadu File Format Support:\n",
    "Malformed component mapping (cmap) box encountered in JP2-family data source.  The body of the box does not appear to contain any channel mappings.\0"
  },
  {
    "E(jp2.cpp)", 68,
    "Error in Kakadu File Format Support:\n",
    "Malformed component mapping (cmap) box encountered in JP2-family data source.  Invalid or truncated mapping specs.\0"
  },
  {
    "E(jp2.cpp)", 69,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source appears to contain a Component Mapping (cmap) box without any matching Palette (pclr) box.  Palette and Component Mapping boxes must be in one-to-one correspondence.\0"
  },
  {
    "E(jp2.cpp)", 70,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source appears to contain an illegal Component Mapping (cmap) box, one of whose channels refers to a non-existent image component or palette lookup table.\0"
  },
  {
    "E(jp2.cpp)", 74,
    "Error in Kakadu File Format Support:\n",
    "Malformed channel definition (cdef) box found in JP2-family data source.  Missing or invalid fields.\0"
  },
  {
    "E(jp2.cpp)", 75,
    "Error in Kakadu File Format Support:\n",
    "Malformed channel definition (cdef) box found in JP2-family data source.  Missing or invalid channel association information.\0"
  },
  {
    "E(jp2.cpp)", 76,
    "Error in Kakadu File Format Support:\n",
    "Malformed channel definition (cdef) box found in JP2-family data source.  The box appears to provide multiple channels with the same Assoc/Typ values.\0"
  },
  {
    "E(jp2.cpp)", 77,
    "Error in Kakadu File Format Support:\n",
    "Malformed channel definition (cdef) box found in JP2-family data source.  The box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 78,
    "Error in Kakadu File Format Support:\n",
    "Malformed opacity (opct) box found in JPX data source.  Failed to read valid Otyp field.\0"
  },
  {
    "E(jp2.cpp)", 79,
    "Error in Kakadu File Format Support:\n",
    "Malformed opacity (opct) box found in JPX data source.  Failed to read valid Nch field.\0"
  },
  {
    "E(jp2.cpp)", 80,
    "Error in Kakadu File Format Support:\n",
    "Malformed opacity (opct) box found in JPX data source.  The box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 81,
    "Error in Kakadu File Format Support:\n",
    "A `jp2_channels' object indicates the presence of more colour channels than the number which is associated with the specified colour space.  This may happen while reading a JP2-family data source which contains an illegal channel definitions (cdef) box, or it may happen while writing a JP2-family file if the `jp2_channels' object has been incorrectly initialized.\0"
  },
  {
    "E(jp2.cpp)", 82,
    "Error in Kakadu File Format Support:\n",
    "Malformed opacity (opct) box encountered in a JPX file indicates a different number of colour channels to that associated with the specified colour space.\0"
  },
  {
    "E(jp2.cpp)", 83,
    "Error in Kakadu File Format Support:\n",
    "The chroma-key feature offered by the `jp2_channels' interface may not be used in conjunction with opacity or pre-multiplied opacity channels.\0"
  },
  {
    "E(jp2.cpp)", 84,
    "Error in Kakadu File Format Support:\n",
    "Malformed channel definition (cdef) box found in JP2-family data source.  The box appears to provide multiple channels with the same Assoc/Typ values.\0"
  },
  {
    "E(jp2.cpp)", 85,
    "Error in Kakadu File Format Support:\n",
    "Incomplete set of colour channel definitions found in a `jp2_channels' object.  This is likely due to a malformed channel definitions (cdef) box in the JP2-family data source.\0"
  },
  {
    "E(jp2.cpp)", 86,
    "Error in Kakadu File Format Support:\n",
    "Malformed opacity (opct) box in JPX data source.  The length of a chroma key specification is incompatible with the bit-depths of the colour channels.\0"
  },
  {
    "E(jp2.cpp)", 88,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write a JPX opacity box with chroma key values for more than 255 channels.  This is not possible within the syntactic constraints of the opct box.\0"
  },
  {
    "E(jp2.cpp)", 91,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source contains multiple instances of the resolution (res) box within the same JP2 header box or compositing layer header box!\0"
  },
  {
    "E(jp2.cpp)", 92,
    "Error in Kakadu File Format Support:\n",
    "The JP2 resolution box must contain at least one of the capture or display resolution sub-boxes.\0"
  },
  {
    "E(jp2.cpp)", 93,
    "Error in Kakadu File Format Support:\n",
    "Malformed resolution box found in JP2-family data source.  Box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 94,
    "Error in Kakadu File Format Support:\n",
    "Malformed capture or display resolution sub-box found in JP2-family data source.  Insufficient or illegal data fields.\0"
  },
  {
    "E(jp2.cpp)", 95,
    "Error in Kakadu File Format Support:\n",
    "Malformed capture or display resolution sub-box found in JP2-family data source.  Box appears to be too long.\0"
  },
  {
    "E(jp2.cpp)", 96,
    "Error in Kakadu File Format Support:\n",
    "Unable to save resolution information having illegal or ridiculously small or large values!\0"
  },
  {
    "E(jp2.cpp)", 97,
    "Error in Kakadu File Format Support:\n",
    "Embedded ICC profile in JP2 colour description box does not have a complete header.\0"
  },
  {
    "E(jp2.cpp)", 98,
    "Error in Kakadu File Format Support:\n",
    "Unknown colour space signature found in embedded ICC profile within a JP2-family data source's colour description (colr) box.\0"
  },
  {
    "E(jp2.cpp)", 99,
    "Error in Kakadu File Format Support:\n",
    "Unknown PCS signature found in embedded ICC profile within a JP2-family data source's colour description (colr) box.\0"
  },
  {
    "E(jp2.cpp)", 100,
    "Error in Kakadu File Format Support:\n",
    "Embedded ICC profile in JP2 colour description box appears to have been truncated!\0"
  },
  {
    "E(jp2.cpp)", 101,
    "Error in Kakadu File Format Support:\n",
    "Embedded ICC profile in JP2 colour description box specifies a display profile, but does not contain a complete set of tone reproduction curves!  This condition is not compatible with any legal ICC profile.\0"
  },
  {
    "E(jp2.cpp)", 102,
    "Error in Kakadu File Format Support:\n",
    "Embedded ICC profile in JP2 colour description box specifies a 3 colour display profile, but does not contain a complete set of primary colorant specifications.\0"
  },
  {
    "E(jp2.cpp)", 103,
    "Error in Kakadu File Format Support:\n",
    "Illegal tag offset or length value supplied in the JP2 embedded icc profile.\0"
  },
  {
    "E(jp2.cpp)", 104,
    "Error in Kakadu File Format Support:\n",
    "Did not find a valid `curv' data type in the embedded ICC profile's tone reproduction curve tag.\0"
  },
  {
    "E(jp2.cpp)", 105,
    "Error in Kakadu File Format Support:\n",
    "The `curv' data type used to represent an embedded ICC profile's tone reproduction curve appears to have been truncated.\0"
  },
  {
    "E(jp2.cpp)", 106,
    "Error in Kakadu File Format Support:\n",
    "Illegal tag offset or length value supplied in JP2 embedded icc profile.\0"
  },
  {
    "E(jp2.cpp)", 107,
    "Error in Kakadu File Format Support:\n",
    "Did not find a valid `XYZ ' data type in the embedded ICC profile's colorant description tag.\0"
  },
  {
    "E(jp2.cpp)", 108,
    "Error in Kakadu File Format Support:\n",
    "Malformed colour description (colr) box found in JP2-family data source.  Insufficient fields, or illegal `approx' or `meth' field found in box.\0"
  },
  {
    "E(jp2.cpp)", 109,
    "Error in Kakadu File Format Support:\n",
    "Malformed colour description (colr) box found in JP2-family data source.  Box appears to terminate prematurely.\0"
  },
  {
    "E(jp2.cpp)", 110,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source terminated unexpectedly inside the colour specification (colr) box.\0"
  },
  {
    "E(jp2.cpp)", 111,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source terminated unexpectedly inside the colour specification (colr) box.\0"
  },
  {
    "E(jp2.cpp)", 112,
    "Error in Kakadu File Format Support:\n",
    "JP2-family data source terminated unexpectedly; unable to read all EP parameter fields for CIELab or CIEJab enumerated colour space.\0"
  },
  {
    "E(jp2.cpp)", 113,
    "Error in Kakadu File Format Support:\n",
    "Malformed JP2 colour description (colr) box found in JP2-family data source.  The box appears to be too large.\0"
  },
  {
    "E(jp2.cpp)", 114,
    "Error in Kakadu File Format Support:\n",
    "No colour description found in JP2-family data source, or provided for generating a JP2-family file!\0"
  },
  {
    "E(jp2.cpp)", 123,
    "Error in Kakadu File Format Support:\n",
    "Currently can only construct profiles having gamma values greater than or equal to 1.0.\0"
  },
  {
    "E(jp2.cpp)", 125,
    "Error in Kakadu File Format Support:\n",
    "Currently can only construct profiles having gamma values greater than or equal to 1.0.\0"
  },
  {
    "E(jp2.cpp)", 126,
    "Error in Kakadu File Format Support:\n",
    "Encountered a JP2 Header box having data which does not belong to any defined sub-box.\0"
  },
  {
    "E(jp2.cpp)", 129,
    "Error in Kakadu File Format Support:\n",
    "Unable to open JP2 file.  Perhaps the file contains no box headers, or perhaps you forgot to call or check the return value from `jp2_source::open' before invoking `jp2_source::read_header'.\0"
  },
  {
    "E(jp2.cpp)", 130,
    "Error in Kakadu File Format Support:\n",
    "Source supplied to `jp2_source::open' does not contain a valid JP2 header.\0"
  },
  {
    "E(jp2.cpp)", 131,
    "Error in Kakadu File Format Support:\n",
    "JP2 source does not commence with a valid signature box.\0"
  },
  {
    "E(jp2.cpp)", 132,
    "Error in Kakadu File Format Support:\n",
    "JP2 source contains a malformed file type box.\0"
  },
  {
    "E(jp2.cpp)", 133,
    "Error in Kakadu File Format Support:\n",
    "JP2 source contains a file type box whose compatibility list does not include JP2.\0"
  },
  {
    "E(jp2.cpp)", 134,
    "Error in Kakadu File Format Support:\n",
    "A contiguous codestream box has been encountered within the JP2 source without first finding both the file-type box and the image header box.\0"
  },
  {
    "E(jp2.cpp)", 139,
    "Error in Kakadu File Format Support:\n",
    "Malformed data reference box (dtbl) found in JPX data source.  Not all fields were present.\0"
  },
  {
    "E(jp2.cpp)", 140,
    "Error in Kakadu File Format Support:\n",
    "Malformed data reference box (dtbl).  Unable to read sufficient correctly formatted data entry URL boxes.\0"
  },
  {
    "E(jp2.cpp)", 141,
    "Error in Kakadu File Format Support:\n",
    "Malformed data reference box (dtbl).  Box appears to contain additional content beyond the declared number of data entry URL boxes.\0"
  },
  {
    "E(jp2.cpp)", 688260352,
    "Error in Kakadu File Format Support:\n",
    "Attempting to embed a codestream which does not conform to Part-1 of the JPEG2000 standard within a plain JP2 file.  For this, you must either write a raw codestream, or embed the codestream within the more advanced JPX file format.\0"
  },
  {
    "E(jp2_shared.h)", 0,
    "Error in Kakadu File Format Support:\n",
    "Attempting to associate a reproduction function (e.g., colour intensity, opacity, etc.) with a non-existent image channel in a JP2-family file.  The problem may be a missing or invalid Component Mapping (cmap) box, or a corrupt or illegal Channel Definitions (cdef) box.\0"
  }
};

static bool dummy_val = kdl_register_text(data,78);

#ifndef KDU_EXCLUDE_DEVELOPER_TEXT

static kdl_message_info dev_data[78] = {
  {
    "E(jp2.cpp)", 0,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_src' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 2,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_src' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 3,
    "Error in Kakadu File Format Support:\n",
    "The `kdu_compressed_source' object supplied to `jp2_family_src::open' must support sequential reading.\0"
  },
  {
    "E(jp2.cpp)", 4,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_src' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 9,
    "Error in Kakadu File Format Support:\n",
    "Attempting to call `jp2_input_box::open' without first closing the box.\0"
  },
  {
    "E(jp2.cpp)", 10,
    "Error in Kakadu File Format Support:\n",
    "Invoking `jp2_input_box::open' with a `jp2_locator' object which references an invalid original file location.\0"
  },
  {
    "E(jp2.cpp)", 11,
    "Error in Kakadu File Format Support:\n",
    "Invoking `jp2_input_box::open' with a `jp2_locator' object which references an invalid original file location.\0"
  },
  {
    "E(jp2.cpp)", 14,
    "Error in Kakadu File Format Support:\n",
    "Attempting to call `jp2_input_box::open' without first closing the box.\0"
  },
  {
    "E(jp2.cpp)", 15,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a sub-box of a box which is not itself open, or which has already been locked by another open sub-box which has not yet been closed.\0"
  },
  {
    "E(jp2.cpp)", 16,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a sub-box of a contiguous codestream box (may be a stream equivalent contiguous codestream for a real original box, which might have had sub-boxes), but you should have checked.\0"
  },
  {
    "E(jp2.cpp)", 17,
    "Error in Kakadu File Format Support:\n",
    "You may not use `jp2_input_box::open_next' unless the object has been previously used to open and then close a box within the source.\0"
  },
  {
    "E(jp2.cpp)", 18,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `jp2_input_box::transplant' on a box which is currently open, or using a donor which is not currently open.\0"
  },
  {
    "E(jp2.cpp)", 19,
    "Error in Kakadu File Format Support:\n",
    "Attempting to seek inside a JP2 box which is not open, or is sharing its read pointer with an open sub-box.\0"
  },
  {
    "E(jp2.cpp)", 20,
    "Error in Kakadu File Format Support:\n",
    "Illegal attempt to read from a JP2 box which is either not open or else has an open sub-box.\0"
  },
  {
    "E(jp2.cpp)", 21,
    "Error in Kakadu File Format Support:\n",
    "Caching source does not appear to support seeking!\0"
  },
  {
    "E(jp2.cpp)", 23,
    "Error in Kakadu File Format Support:\n",
    "Non-seekable JP2 sources must be read sequentially.  You are probably trying to read from multiple boxes simultaneously.\0"
  },
  {
    "E(jp2.cpp)", 24,
    "Error in Kakadu File Format Support:\n",
    "Attempting to read a 2-byte word from a JP2 box, after first reading a partial 4-byte word!\0"
  },
  {
    "E(jp2.cpp)", 25,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_tgt' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 27,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_tgt' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 28,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_output_box' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 29,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_output_box' to write to a `jp2_family_tgt' object which already contains a rubber length box.  Any rubber length box must be the last box in the data stream.\0"
  },
  {
    "E(jp2.cpp)", 30,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_output_box' object which is already open.\0"
  },
  {
    "E(jp2.cpp)", 31,
    "Error in Kakadu File Format Support:\n",
    "You cannot call `jp2_output_box::open_next' on a box which has never been opened either as a sub-box of another box or as a top-level box within a valid `jp2_family_tgt' object.\0"
  },
  {
    "E(jp2.cpp)", 32,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set a rubber length for a JP2 box whose total length has already been declared, or is to be written at the end.\0"
  },
  {
    "E(jp2.cpp)", 33,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set a rubber length for a JP2 box which is currently inside a rewrite section.\0"
  },
  {
    "E(jp2.cpp)", 34,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set the target size of a JP2 box which has already been assigned a rubber length.\0"
  },
  {
    "E(jp2.cpp)", 35,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set the target size of a JP2 box whose content length is already known, or is to be written at the end.\0"
  },
  {
    "E(jp2.cpp)", 36,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set the target size of a JP2 box which is currently inside a rewrite section.\0"
  },
  {
    "E(jp2.cpp)", 37,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set the target size of a JP2 box to which a larger number of bytes has already been written.\0"
  },
  {
    "E(jp2.cpp)", 38,
    "Error in Kakadu File Format Support:\n",
    "You cannot use `jp2_output_box::write_header_last' unless the box is open.\0"
  },
  {
    "E(jp2.cpp)", 39,
    "Error in Kakadu File Format Support:\n",
    "You cannot use `jp2_output_box::write_header_last' unless this is a top level box and the underlying `jp2_family_tgt' object represents a file.\0"
  },
  {
    "E(jp2.cpp)", 40,
    "Error in Kakadu File Format Support:\n",
    "Attempting to close an output JP2 box whose length was defined ahead of time, having written less bytes than indicated by that length value.\0"
  },
  {
    "E(jp2.cpp)", 41,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write more bytes to a JP2 output box than the number which was specified via a previous call to `jp2_output_box::set_target_size'.\0"
  },
  {
    "E(jp2.cpp)", 42,
    "Error in Kakadu File Format Support:\n",
    "Attempting to read a JP2 image header box (ihdr) into a `jp2_dimensions' object which has previously been initialized!\0"
  },
  {
    "E(jp2.cpp)", 50,
    "Error in Kakadu File Format Support:\n",
    "Incomplete or invalid dimensional information provided when initializing a `jp2_dimensions' object.\0"
  },
  {
    "E(jp2.cpp)", 51,
    "Error in Kakadu File Format Support:\n",
    "Invalid compression type value provided when initializing a `jp2_dimensions' object.\0"
  },
  {
    "E(jp2.cpp)", 52,
    "Error in Kakadu File Format Support:\n",
    "JP2 dimensions may be initialized only once!\0"
  },
  {
    "E(jp2.cpp)", 53,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_dimensions' object using an incomplete `siz_params' object.\0"
  },
  {
    "E(jp2.cpp)", 54,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_dimensions' object using an incomplete `siz_params' object.\0"
  },
  {
    "E(jp2.cpp)", 55,
    "Error in Kakadu File Format Support:\n",
    "Trying to copy a `jp2_palette' object to another object which has already been initialized.  Reinitialization is not permitted.\0"
  },
  {
    "E(jp2.cpp)", 56,
    "Error in Kakadu File Format Support:\n",
    "Attempting to read a JP2 palette box (pclr) into a `jp2_palette' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 62,
    "Error in Kakadu File Format Support:\n",
    "Incomplete or invalid information provided when initializing a `jp2_palette' object.\0"
  },
  {
    "E(jp2.cpp)", 63,
    "Error in Kakadu File Format Support:\n",
    "A `jp2_palette' object may be initialized only once!\0"
  },
  {
    "E(jp2.cpp)", 64,
    "Error in Kakadu File Format Support:\n",
    "Trying to copy an internal `j2_component_map' object to another object which has already been initialized.  This is an internal fault within the file format reading/writing logic.\0"
  },
  {
    "E(jp2.cpp)", 65,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `j2_component_map' object multiple times.  Problem encountered while parsing a JP2 Component Mapping (cmap) box!\0"
  },
  {
    "E(jp2.cpp)", 71,
    "Error in Kakadu File Format Support:\n",
    "Attempting to create a Component Mapping (cmap) box, one of whose channels refers to a non-existent image component or palette lookup table.\0"
  },
  {
    "E(jp2.cpp)", 72,
    "Error in Kakadu File Format Support:\n",
    "Trying to copy a `jp2_channels' object to another object which has already been initialized.  Reinitialization is not permitted.\0"
  },
  {
    "E(jp2.cpp)", 73,
    "Error in Kakadu File Format Support:\n",
    "Attempting to read a JP2 channel definitions (cdef) or JPX opacity (opct) box into a `j2_channels' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 87,
    "Error in Kakadu File Format Support:\n",
    "Attempting to create a JPX file which uses chroma-keys in an incompatible manner across compositing layers which share a common codestream.  The JPX file format has insufficient flexibility in its channel mapping rules to allow arbitrary binding between image components and colour channels at the same time as chroma keying.\0"
  },
  {
    "E(jp2.cpp)", 89,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_channels' object multiple times.  `jp2_channels::init' may be applied only to an object which is not yet initialized.\0"
  },
  {
    "E(jp2.cpp)", 90,
    "Error in Kakadu File Format Support:\n",
    "JP2 resolution information may be initialized only once!\0"
  },
  {
    "E(jp2.cpp)", 115,
    "Error in Kakadu File Format Support:\n",
    "The sample precisions specified when initializing a `jp2_colour' object to represent a CIE Lab or Jab colour space do not agree with the actual precisions of the relevant codestream image components or palette lookup tables.\0"
  },
  {
    "E(jp2.cpp)", 116,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 117,
    "Error in Kakadu File Format Support:\n",
    "Unrecognized colour space identifier supplied to `jp2_colour::init'.\0"
  },
  {
    "E(jp2.cpp)", 118,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 119,
    "Error in Kakadu File Format Support:\n",
    "The second form of the `jp2_colour::init' function may be used only to initialize an Lab or Jab colour description.  The supplied `space' argument is neither JP2_CIELab_SPACE nor JP2_CIEJab_SPACE, though.\0"
  },
  {
    "E(jp2.cpp)", 120,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 121,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 122,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 124,
    "Error in Kakadu File Format Support:\n",
    "Attempting to initialize a `jp2_colour' object which has already been initialized.\0"
  },
  {
    "E(jp2.cpp)", 127,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write a JP2 opacity (opct) box to the image header box of a baseline JP2 file.  This box type is defined by JPX, not JP2, and is required only if you are trying to record chroma-key information.  You might like to upgrade the application to write files using the `jpx_target' object, rather than `jp2_target'.\0"
  },
  {
    "E(jp2.cpp)", 128,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write a colour description (colr) box which uses JPX extended features to the image header of a baseline JP2 file.  You might like to upgrade the application to write files using the `jpx_target' object, rather than `jp2_target'.\0"
  },
  {
    "E(jp2.cpp)", 135,
    "Error in Kakadu File Format Support:\n",
    "The `jp2_target::open' function must be supplied with a `jp2_family_tgt' object to which nothing has yet been written.\0"
  },
  {
    "E(jp2.cpp)", 136,
    "Error in Kakadu File Format Support:\n",
    "You may not call `jp2_target::write_header' until after you have called `jp2_target::open'.\0"
  },
  {
    "E(jp2.cpp)", 137,
    "Error in Kakadu File Format Support:\n",
    "At the point when `jp2_target::write_header' is called, no other information should have been written to the `jp2_family_tgt' object with which it was opened.\0"
  },
  {
    "E(jp2.cpp)", 138,
    "Error in Kakadu File Format Support:\n",
    "You may not call `jp2_target::open_codestream' until after you have called `jp2_target::open' and `jp2_target::write_header'.\0"
  },
  {
    "E(jp2.cpp)", 142,
    "Error in Kakadu File Format Support:\n",
    "Current implementation of `j2_data_references::save_box' can only write JPX formatted data reference boxes -- i.e., those with box type `dtbl' rather than `dref'.  However, the implementation can easily be expanded.\0"
  },
  {
    "E(jp2.cpp)", 143,
    "Error in Kakadu File Format Support:\n",
    "Trying to add too many URL's to the `jp2_data_references' object.  At most 2^16 - 1 URL's may be stored by the data references box.\0"
  },
  {
    "E(jp2.cpp)", 34672641,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set a rubber length for a JP2 box for which `jp2_output_box::use_long_headers' has been called -- rubber length boxes must use the short (8 byte) header style.\0"
  },
  {
    "E(jp2.cpp)", 34672642,
    "Error in Kakadu File Format Support:\n",
    "You cannot call `jp2_output_box::use_long_header' unless the box is open.\0"
  },
  {
    "E(jp2.cpp)", 51449859,
    "Error in Kakadu File Format Support:\n",
    "You cannot call `jp2_output_box::use_long_header' if the JP2 box in question has already been assigned a rubber length -- rubber lengths must be written using the short header format with 8 bytes instead of 16 bytes.\0"
  },
  {
    "E(jp2.cpp)", 134550017,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `jp2_input_box::fork' on a box which is currently open, or using a forking source which is not currently open.\0"
  },
  {
    "E(jp2.cpp)", 386339329,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write beyond the end of a re-opened JP2 output box.\0"
  },
  {
    "E(jp2.cpp)", 386339330,
    "Error in Kakadu File Format Support:\n",
    "When invoking `jp2_output_box::write_free_and_close', the supplied length for the free box to be written at the end must be >= 8 bytes, in order to accommodate the header length.\0"
  },
  {
    "E(jp2.cpp)", 386339331,
    "Error in Kakadu File Format Support:\n",
    "When invoking `jp2_output_box::write_free_and_close' on a JP2 output box whose total size is fixed/known, the `free' sub-box to be written before closure must precisely span all remaining bytes in the box.\0"
  },
  {
    "E(jp2.cpp)", 402919937,
    "Error in Kakadu File Format Support:\n",
    "Attempting to call `jp2_input_box::open_as' without first closing the box.\0"
  },
  {
    "E(jp2.cpp)", 402919938,
    "Error in Kakadu File Format Support:\n",
    "Attempting to call `jp2_input_box::open_as' with a NULL `jp2_family_src' reference.\0"
  },
  {
    "E(jp2.cpp)", 637864193,
    "Error in Kakadu File Format Support:\n",
    "Attempting to open a `jp2_family_tgt' object which is already open.\0"
  }
};

static bool dev_dummy_val = kdl_register_text(dev_data,78);

#endif // !KDU_EXCLUDE_DEVELOPER_TEXT
