// -----------------------------------------------------------------
// This file is automatically generated by "kdu_text_extractor"
// Do not edit the file directly.  You may, however, use this file
// as a template for alternate versions in which the text strings
// are translated into different languages.
// -----------------------------------------------------------------
#include <kdu_messaging.h>

struct kdl_message_info{
  const char *context;
  kdu_uint32 id;
  const char *lead_in;
  const char *text;
};

static bool
  kdl_register_text(kdl_message_info *info, int num_records)
{
  for (; num_records > 0; num_records--, info++)
    kdu_customize_text(info->context,info->id,
                       info->lead_in,info->text);
  return true;
}

static kdl_message_info data[73] = {
  {
    "E(mj2.cpp)", 0,
    "Error in Kakadu File Format Support:\n",
    "MJ2 track contains multiple STSZ (Sample Size) boxes.\0"
  },
  {
    "E(mj2.cpp)", 1,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSZ (Sample Size) box  found in Motion JPEG2000 data source.  Insufficient or illegal fields encountered.  Version and flags must both be zero.\0"
  },
  {
    "E(mj2.cpp)", 2,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSZ (Sample Size) box found in Motion JPEG2000 data source.  Box contains insufficient sample size data to accommodate all samples.\0"
  },
  {
    "E(mj2.cpp)", 3,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSZ (Sample Size) box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 4,
    "Error in Kakadu File Format Support:\n",
    "MJ2 track contains multiple STCO (Chunk Offset) boxes.\0"
  },
  {
    "E(mj2.cpp)", 5,
    "Error in Kakadu File Format Support:\n",
    "Malformed STCO (Chunk Offset) box found in Motion JPEG2000 data source.  Insufficient or illegal fields encountered.  Version and flags must both be zero.\0"
  },
  {
    "E(mj2.cpp)", 6,
    "Error in Kakadu File Format Support:\n",
    "Malformed STCO (Chunk Offset) box found in Motion JPEG2000 data source.  Box contains insufficient sample size data to accommodate all samples.\0"
  },
  {
    "E(mj2.cpp)", 8,
    "Error in Kakadu File Format Support:\n",
    "Malformed STCO (Chunk Offset) box found in Motion JPEG2000 data source.  Box contains insufficient sample size data to accommodate all samples.\0"
  },
  {
    "E(mj2.cpp)", 10,
    "Error in Kakadu File Format Support:\n",
    "Malformed STCO (Chunk Offset) box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 11,
    "Error in Kakadu File Format Support:\n",
    "MJ2 track contains multiple STSC (Sample to Chunk) boxes.\0"
  },
  {
    "E(mj2.cpp)", 12,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSC (Sample to Chunk) box found in Motion JPEG2000 data source.  Insufficient or illegal fields encountered.  Version and flags must both be zero.\0"
  },
  {
    "E(mj2.cpp)", 13,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSC (Sample to Chunk) box found in Motion JPEG2000 data source.  Insufficient fields found inside box.\0"
  },
  {
    "E(mj2.cpp)", 14,
    "Error in Kakadu File Format Support:\n",
    "Found reference to non-initial sample description in a STSC (Sample to Chunk) box within the Motion JPEG2000 data source.  While this is legal, the current implementation supports only single description tracks, which is consistent with simpler Motion JPEG2000 profiles.\0"
  },
  {
    "E(mj2.cpp)", 15,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSC (Sample to Chunk) box found in Motion JPEG2000 data source.  The `first_chunk' indices associated with successive list elements must be strictly increasing.\0"
  },
  {
    "E(mj2.cpp)", 16,
    "Error in Kakadu File Format Support:\n",
    "Malformed STSC (Sample to Chunk) box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 17,
    "Error in Kakadu File Format Support:\n",
    "MJ2 track contains multiple STTS (Time to Sample) boxes.\0"
  },
  {
    "E(mj2.cpp)", 18,
    "Error in Kakadu File Format Support:\n",
    "Malformed STTS (Time to Sample) box found in Motion JPEG2000 data source.  Insufficient or illegal fields encountered.  Version and flags must both be zero.\0"
  },
  {
    "E(mj2.cpp)", 19,
    "Error in Kakadu File Format Support:\n",
    "Malformed STTS (Time to Sample) box found in Motion JPEG2000 data source.  Box terminated unexpectedly.\0"
  },
  {
    "E(mj2.cpp)", 20,
    "Error in Kakadu File Format Support:\n",
    "Malformed STTS (Time to Sample) box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 21,
    "Error in Kakadu File Format Support:\n",
    "Malformed track header box found in Motion JPEG2000 data source.  Version number must be 1 or 0.\0"
  },
  {
    "E(mj2.cpp)", 22,
    "Error in Kakadu File Format Support:\n",
    "Malformed track header box found in Motion JPEG2000 data source.  Box terminated prematurely.\0"
  },
  {
    "E(mj2.cpp)", 23,
    "Error in Kakadu File Format Support:\n",
    "Malformed track header box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 24,
    "Error in Kakadu File Format Support:\n",
    "Presentation volume too large to be correctly represented in MJ2 track header box.\0"
  },
  {
    "E(mj2.cpp)", 25,
    "Error in Kakadu File Format Support:\n",
    "Non-trivial elements of the video transformation matrix must be representable as 16.16 signed fixed point numbers.\0"
  },
  {
    "E(mj2.cpp)", 26,
    "Error in Kakadu File Format Support:\n",
    "The last row of the video transformation matrix must be representable as 2.30 signed fixed point numbers.\0"
  },
  {
    "E(mj2.cpp)", 27,
    "Error in Kakadu File Format Support:\n",
    "Malformed media header box found in Motion JPEG2000 data source.  Version number must be 1 or 0.\0"
  },
  {
    "E(mj2.cpp)", 28,
    "Error in Kakadu File Format Support:\n",
    "Malformed media header box found in Motion JPEG2000 data source.  Box terminated prematurely.\0"
  },
  {
    "E(mj2.cpp)", 29,
    "Error in Kakadu File Format Support:\n",
    "Malformed media header box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 30,
    "Error in Kakadu File Format Support:\n",
    "Malformed media handler box found in Motion JPEG2000 data source.  Version number must be 0.\0"
  },
  {
    "E(mj2.cpp)", 31,
    "Error in Kakadu File Format Support:\n",
    "Malformed meda handler box found in Motion JPEG2000 data source.  Box terminated prior to the appearance of a media handler identifier (a 4-character-code).\0"
  },
  {
    "E(mj2.cpp)", 32,
    "Error in Kakadu File Format Support:\n",
    "Malformed data reference box found in Motion JPEG2000 data source.  Version number must be 0.\0"
  },
  {
    "E(mj2.cpp)", 33,
    "Error in Kakadu File Format Support:\n",
    "Malformed data reference box found in Motion JPEG2000 data source.  Box appears to terminate prematurely.\0"
  },
  {
    "E(mj2.cpp)", 34,
    "Error in Kakadu File Format Support:\n",
    "Malformed sample description box found in Motion JPEG2000 data source.  Version number must be 0.\0"
  },
  {
    "E(mj2.cpp)", 35,
    "Error in Kakadu File Format Support:\n",
    "Malformed sample description box found in Motion JPEG2000 data source.  Box terminates prematurely.\0"
  },
  {
    "E(mj2.cpp)", 36,
    "Error in Kakadu File Format Support:\n",
    "No track header box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 37,
    "Error in Kakadu File Format Support:\n",
    "No media header box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 38,
    "Error in Kakadu File Format Support:\n",
    "No media handler box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 39,
    "Error in Kakadu File Format Support:\n",
    "No sample description box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 40,
    "Error in Kakadu File Format Support:\n",
    "No time to sample box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 41,
    "Error in Kakadu File Format Support:\n",
    "No sample to chunk box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 42,
    "Error in Kakadu File Format Support:\n",
    "No sample size box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 43,
    "Error in Kakadu File Format Support:\n",
    "No chunk offset box found in Motion JPEG2000 track.\0"
  },
  {
    "E(mj2.cpp)", 44,
    "Error in Kakadu File Format Support:\n",
    "Unable to write to output device; disk may be full.\0"
  },
  {
    "E(mj2.cpp)", 45,
    "Error in Kakadu File Format Support:\n",
    "Malformed video media header box (VMHD) found in Motion JPEG2000 data source.  Box terminated prematurely.\0"
  },
  {
    "E(mj2.cpp)", 47,
    "Error in Kakadu File Format Support:\n",
    "Malformed video sample entry box in Motion JPEG2000 data source.  Failed to locate the embedded JP2 header box.\0"
  },
  {
    "E(mj2.cpp)", 48,
    "Error in Kakadu File Format Support:\n",
    "Failed to completely read the JP2 header embedded in a Motion JPEG2000 data source's visual sample entry box.  It is likely that you are attempting to open a motion JPEG2000 stream from a dynamic cache (any object derived from `kdu_cache2').\0"
  },
  {
    "E(mj2.cpp)", 49,
    "Error in Kakadu File Format Support:\n",
    "Malformed field coding box found inside a video sample entry box in the Motion JPEG2000 data source.  The body of the field coding box should consist of 2 single byte quantities representing the number of fields (1 or 2) and the field order, (values 0, 1 or 6).\0"
  },
  {
    "E(mj2.cpp)", 50,
    "Error in Kakadu File Format Support:\n",
    "Malformed field coding box found inside a video sample entry box in the Motion JPEG2000 data source.  The box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 51,
    "Error in Kakadu File Format Support:\n",
    "Attempting to save a video track to which a whole frame has not yet been written.  For interlaced frames, at least two fields must be written to constitute a whole frame.\0"
  },
  {
    "E(mj2.cpp)", 52,
    "Error in Kakadu File Format Support:\n",
    "Recommended display resolutions must be small enough to fit inside a 16.16 signed fixed point representation for recording in the MJ2 Sample Description box.   Typical values are 72 dpi.\0"
  },
  {
    "E(mj2.cpp)", 54,
    "Error in Kakadu File Format Support:\n",
    "Motion JPEG2000 data source terminated prematurely!  Not all of the indicated sample data appears to be available.\0"
  },
  {
    "E(mj2.cpp)", 55,
    "Error in Kakadu File Format Support:\n",
    "Index tables in Motion JPEG2000 data source appear to be corrupt.  Failed to find a valid JP2 code-stream box at the location identified in the file.\0"
  },
  {
    "E(mj2.cpp)", 59,
    "Error in Kakadu File Format Support:\n",
    "Motion JPEG2000 data source terminated prematurely!  Not all of the indicated sample data appears to be available.\0"
  },
  {
    "E(mj2.cpp)", 60,
    "Error in Kakadu File Format Support:\n",
    "Index tables in Motion JPEG2000 data source appear to be corrupt.  Failed to find a valid JP2 code-stream box at the location identified in the file.\0"
  },
  {
    "E(mj2.cpp)", 61,
    "Error in Kakadu File Format Support:\n",
    "Motion JPEG2000 data source terminated prematurely!  Not all of the indicated sample data appears to be available.\0"
  },
  {
    "E(mj2.cpp)", 62,
    "Error in Kakadu File Format Support:\n",
    "Index tables in Motion JPEG2000 data source appear to be corrupt.  Failed to find a valid JP2 code-stream box at the location identified in the file.\0"
  },
  {
    "E(mj2.cpp)", 74,
    "Error in Kakadu File Format Support:\n",
    "Malformed movie header box found in Motion JPEG2000 data source.  Version number must be 1 or 0.\0"
  },
  {
    "E(mj2.cpp)", 75,
    "Error in Kakadu File Format Support:\n",
    "Malformed movie header box found in Motion JPEG2000 data source.  Box terminated prematurely.\0"
  },
  {
    "E(mj2.cpp)", 76,
    "Error in Kakadu File Format Support:\n",
    "Malformed movie header box found in Motion JPEG2000 data source.  Box appears to be too long.\0"
  },
  {
    "E(mj2.cpp)", 77,
    "Error in Kakadu File Format Support:\n",
    "Playback rate too large to be correctly represented in MJ2 movie header box.\0"
  },
  {
    "E(mj2.cpp)", 78,
    "Error in Kakadu File Format Support:\n",
    "Playback volume too large to be correctly represented in MJ2 movie header box.\0"
  },
  {
    "E(mj2.cpp)", 79,
    "Error in Kakadu File Format Support:\n",
    "Non-trivial elements of the video transformation matrix must be representable as 16.16 signed fixed point numbers.\0"
  },
  {
    "E(mj2.cpp)", 80,
    "Error in Kakadu File Format Support:\n",
    "The last row of the video transformation matrix must be representable as 2.30 signed fixed point numbers.\0"
  },
  {
    "E(mj2.cpp)", 81,
    "Error in Kakadu File Format Support:\n",
    "MJP2 data source does not commence with the JP2 family signature box.\0"
  },
  {
    "E(mj2.cpp)", 82,
    "Error in Kakadu File Format Support:\n",
    "MJP2 data source does not contain a JP2 file type box in the correct position -- should be second box in file.\0"
  },
  {
    "E(mj2.cpp)", 83,
    "Error in Kakadu File Format Support:\n",
    "The mandatory file type box within the MJP2 data source, does not include MJP2 in its compatibility list.\0"
  },
  {
    "E(mj2.cpp)", 84,
    "Error in Kakadu File Format Support:\n",
    "Motion JPEG2000 data source does not appear to contain a movie header (MVHD) box.\0"
  },
  {
    "W(mj2.cpp)", 0,
    "Warning in Kakadu File Format Support:\n",
    "The current implementation can only handle Motion JPEG2000 tracks which have single-entry data reference boxes; multiple-entry data reference boxes are only required if the MJ2 file contains external data references -- not currently supported.  Non-conforming tracks will be treated as disabled.\0"
  },
  {
    "W(mj2.cpp)", 1,
    "Warning in Kakadu File Format Support:\n",
    "The current implementation cannot handle Motion JPEG2000 tracks which contain external data references.  Non-conforming tracks will be treated as disabled.\0"
  },
  {
    "W(mj2.cpp)", 2,
    "Warning in Kakadu File Format Support:\n",
    "Current implementation can only handle Motion JPEG2000 tracks with a single-entry sample description box.  Other tracks will be treated as disabled.\0"
  },
  {
    "W(mj2.cpp)", 3,
    "Warning in Kakadu File Format Support:\n",
    "Malformed video media header box (VMHD) found in Motion JPEG2000 data source.  Incorrect version number or least significant flag bit not set.  Ignoring box and using default graphics mode for the track.\0"
  },
  {
    "W(mj2.cpp)", 4,
    "Warning in Kakadu File Format Support:\n",
    "Unrecognized graphics mode encountered in video media header box (VMHD) within Motion JPEG2000 data source.  Proceeding with the default \"copy\" mode.\0"
  },
  {
    "W(mj2.cpp)", 5,
    "Warning in Kakadu File Format Support:\n",
    "The current implementation can only handle Motion JPEG2000 tracks which have single-entry data reference boxes; multiple-entry data reference boxes are only required if the MJ2 file contains external data references -- not currently supported.  Non-conforming tracks will be treated as disabled.\0"
  }
};

static bool dummy_val = kdl_register_text(data,73);

#ifndef KDU_EXCLUDE_DEVELOPER_TEXT

static kdl_message_info dev_data[17] = {
  {
    "E(mj2.cpp)", 7,
    "Error in Kakadu File Format Support:\n",
    "Chunk offset found in Motion JPEG2000 data STCO (Chunk Offset) box is too large to be represented as a signed 32-bit integer.  To avoid this problem, recompile the Kakadu software to work with 64-bit variants of the \"kdu_long\" primitive data type.\0"
  },
  {
    "E(mj2.cpp)", 9,
    "Error in Kakadu File Format Support:\n",
    "Chunk offset found in Motion JPEG2000 data STCO (Chunk Offset) box is too large to be represented as a signed 32-bit integer.  To avoid this problem, recompile the Kakadu software to work with 64-bit variants of the \"kdu_long\" primitive data type.\0"
  },
  {
    "E(mj2.cpp)", 46,
    "Error in Kakadu File Format Support:\n",
    "Illegal graphics mode cannot be represented in the video media header box (VMHD) within a Motion JPEG2000 data source.\0"
  },
  {
    "E(mj2.cpp)", 53,
    "Error in Kakadu File Format Support:\n",
    "You may not call `mj2_video_source::open_stream' without first closing any image from the same track, opened by `mj2_video_source::open_image'.\0"
  },
  {
    "E(mj2.cpp)", 58,
    "Error in Kakadu File Format Support:\n",
    "You may not call `mj2_video_source::open_image' without first closing any open image from the same track.\0"
  },
  {
    "E(mj2.cpp)", 63,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `mj2_video_source::seek' on an `mj2_video_source' object which currently has no active image.\0"
  },
  {
    "E(mj2.cpp)", 64,
    "Error in Kakadu File Format Support:\n",
    "Attempting to invoke `mj2_video_source::get_pos' on an `mj2_video_source' object which currently has no active image.\0"
  },
  {
    "E(mj2.cpp)", 65,
    "Error in Kakadu File Format Support:\n",
    "Illegal graphics mode supplied for Motion JPEG2000 video track.  Legal values are given by the macros `MJ2_GRAPHICS_COPY', `MJ2_GRAPHICS_BLUE_SCREEN', `MJ2_GRAPHICS_ALPHA', `MJ2_GRAPHICS_PREMULT_ALPHA' and `MJ2_GRAPHICS_COMPONENT_ALPHA'.\0"
  },
  {
    "E(mj2.cpp)", 66,
    "Error in Kakadu File Format Support:\n",
    "Attempting to set the time scale used for a video track after opening one or more fields/frames for that track.\0"
  },
  {
    "E(mj2.cpp)", 67,
    "Error in Kakadu File Format Support:\n",
    "Zero is not a legitimate value for the time scale (number of ticks per second) of a video track.\0"
  },
  {
    "E(mj2.cpp)", 68,
    "Error in Kakadu File Format Support:\n",
    "Attempting to modify the field coding for a video track after opening one or more fields/frames for that track.\0"
  },
  {
    "E(mj2.cpp)", 69,
    "Error in Kakadu File Format Support:\n",
    "You must close the currently open image (field or frame), before opening a new one.\0"
  },
  {
    "E(mj2.cpp)", 70,
    "Error in Kakadu File Format Support:\n",
    "You must set the frame period to a non-zero number of reference clock ticks before attempting to open any video images.\0"
  },
  {
    "E(mj2.cpp)", 71,
    "Error in Kakadu File Format Support:\n",
    "Attempting to close a video image which has not yet been opened\0"
  },
  {
    "E(mj2.cpp)", 72,
    "Error in Kakadu File Format Support:\n",
    "Codestreams being written as successive fields or frames of an MJ2 video track must have compatible dimensions.  For interlaced frames, the field dimensions must be compatible with the declared field placement order and implied frame dimensions.  This means that the two fields of a frame can have different heights only if their heights differ by 1 and then the higher field must be the one whose first line appears at the top of the frame.\0"
  },
  {
    "E(mj2.cpp)", 73,
    "Error in Kakadu File Format Support:\n",
    "Attempting to write compressed data to a video track which has no open video field.\0"
  },
  {
    "E(mj2_local.h)", 0,
    "Error in Kakadu File Format Support:\n",
    "Attempting to complete a Motion JPEG2000 file (writing) without first closing all open video fields.\0"
  }
};

static bool dev_dummy_val = kdl_register_text(dev_data,17);

#endif // !KDU_EXCLUDE_DEVELOPER_TEXT
